import { router } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { useEffect, useState, useCallback } from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '../features/auth';
import { accountOperations, accountService, isProfileCompatible, type NativeFile, type StudentProfile } from '../features/account/index';
import { getApiErrorMessage } from '../shared/lib/api-error';
import { normalizeMediaUrl } from '../shared/lib/media-url';
import { colors, spacing, touchTarget } from '../shared/theme/tokens';

export default function ProfileScreen() {
  const auth = useAuth();
  const [profile, setProfile] = useState<StudentProfile | null>(null);
  const [name, setName] = useState(auth.user?.hoTen ?? '');
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);
  const [avatarFile, setAvatarFile] = useState<NativeFile | undefined>();
  const load = useCallback(async () => { const op = accountOperations.nextProfile(); setLoading(true); setError(null); try { const next = await accountService.getProfile(); if (!accountOperations.isCurrentProfile(op)) return; if (!isProfileCompatible(next, auth)) { await auth.clearSession('role-change'); return; } setProfile(next); setName(next.hoTen); } catch (e) { if (accountOperations.isCurrentProfile(op)) setError(getApiErrorMessage(e)); } finally { if (accountOperations.isCurrentProfile(op)) setLoading(false); } }, [auth]);
  useEffect(() => { void load(); }, [load]);
  const pickAvatar = async () => { setError(null); const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { setError('Cần cấp quyền thư viện ảnh để chọn ảnh đại diện.'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: 0.8 }); if (result.canceled || !result.assets[0]) return; const asset = result.assets[0]; const type = asset.mimeType ?? 'image/jpeg'; const extension = type.split('/')[1] ?? 'jpg'; setAvatarFile({ uri: asset.uri, name: `avatar.${extension}`, type }); };
  const save = async () => { const trimmed = name.trim(); if (trimmed.length < 2 || trimmed.length > 120) { setError('Họ tên phải dài từ 2 đến 120 ký tự.'); return; } if (!profile || (trimmed === profile.hoTen && !avatarFile)) return; setSaving(true); setError(null); try { const next = await accountService.updateProfile(trimmed, avatarFile); if (!isProfileCompatible(next, auth)) { await auth.clearSession('role-change'); return; } setProfile(next); setAvatarFile(undefined); await auth.updateUser({ hoTen: next.hoTen, anhDaiDien: next.anhDaiDien ?? null }); } catch (e) { setError(getApiErrorMessage(e)); } finally { setSaving(false); } };
  const avatar = avatarFile?.uri ?? normalizeMediaUrl(profile?.anhDaiDien ?? auth.user?.anhDaiDien);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>Hồ sơ cá nhân</Text>{loading ? <Text style={styles.muted}>Đang tải hồ sơ...</Text> : null}{error ? <Text style={styles.error}>{error}</Text> : null}{avatar ? <Image source={{ uri: avatar }} style={styles.avatar} accessibilityLabel="Ảnh đại diện" /> : <View style={styles.avatarFallback}><Text style={styles.initial}>{(name.trim()[0] ?? '?').toUpperCase()}</Text></View>}<Pressable accessibilityRole="button" disabled={saving} onPress={() => { void pickAvatar(); }} style={styles.secondary}><Text style={styles.secondaryText}>Chọn ảnh đại diện</Text></Pressable><TextInput accessibilityLabel="Họ và tên" value={name} onChangeText={setName} style={styles.input} /><Text style={styles.label}>Email</Text><Text style={styles.readonly}>{profile?.email ?? auth.user?.email}</Text><Text style={styles.label}>Vai trò</Text><Text style={styles.readonly}>Học viên</Text><Pressable accessibilityRole="button" disabled={saving || loading} onPress={() => { void save(); }} style={styles.button}><Text style={styles.buttonText}>{saving ? 'Đang lưu...' : 'Lưu thay đổi'}</Text></Pressable><Pressable accessibilityRole="button" onPress={() => router.back()} style={styles.link}><Text style={styles.linkText}>Quay lại</Text></Pressable></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.xl, gap: spacing.md }, title: { fontSize: 28, fontWeight: '700', color: colors.text }, muted: { color: colors.textMuted }, error: { color: colors.danger }, avatar: { width: 96, height: 96, borderRadius: 48, alignSelf: 'center' }, avatarFallback: { width: 96, height: 96, borderRadius: 48, alignSelf: 'center', backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, initial: { fontSize: 36, color: colors.primaryDark, fontWeight: '700' }, input: { minHeight: touchTarget, borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: spacing.md, backgroundColor: colors.surface, color: colors.text, fontSize: 16 }, label: { color: colors.textMuted, fontWeight: '600' }, readonly: { color: colors.text, backgroundColor: colors.surface, padding: spacing.md, borderRadius: 10 }, button: { minHeight: touchTarget, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', borderRadius: 10 }, buttonText: { color: colors.surface, fontWeight: '700' }, secondary: { minHeight: touchTarget, borderWidth: 1, borderColor: colors.primary, alignItems: 'center', justifyContent: 'center', borderRadius: 10 }, secondaryText: { color: colors.primaryDark, fontWeight: '700' }, link: { minHeight: touchTarget, justifyContent: 'center', alignItems: 'center' }, linkText: { color: colors.primaryDark, fontWeight: '600' } });
