using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace educodeai_server.Migrations;

public partial class ConsolidateRuntimeSchema : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            ALTER TABLE "DonHangKhoaHocs" ADD COLUMN IF NOT EXISTS "LoaiDonHang" character varying(30) NOT NULL DEFAULT 'COURSE_PURCHASE';
            ALTER TABLE "DonHangKhoaHocs" ADD COLUMN IF NOT EXISTS "TongTienGoc" numeric(18,2) NOT NULL DEFAULT 0;
            ALTER TABLE "DonHangKhoaHocs" ADD COLUMN IF NOT EXISTS "SoTienGiam" numeric(18,2) NOT NULL DEFAULT 0;
            ALTER TABLE "DonHangKhoaHocs" ADD COLUMN IF NOT EXISTS "MaVoucher" integer NULL;
            ALTER TABLE "DonHangKhoaHocs" ADD COLUMN IF NOT EXISTS "CodeVoucher" character varying(40) NULL;
            UPDATE "DonHangKhoaHocs" SET "TongTienGoc" = "TongTien" WHERE "TongTienGoc" = 0;
            ALTER TABLE "MaGiamGias" ADD COLUMN IF NOT EXISTS "MaNguoiTao" integer NOT NULL DEFAULT 1;
            ALTER TABLE "MaGiamGias" ADD COLUMN IF NOT EXISTS "LoaiNguoiTao" character varying(20) NOT NULL DEFAULT 'ADMIN';
            ALTER TABLE "MaGiamGias" ADD COLUMN IF NOT EXISTS "PhamViApDung" character varying(30) NOT NULL DEFAULT 'SPECIFIC_COURSES';
            ALTER TABLE "MaGiamGias" ADD COLUMN IF NOT EXISTS "ChoPhepApDungChoQuaTang" boolean NOT NULL DEFAULT TRUE;
            CREATE TABLE IF NOT EXISTS "MaQuaTangHocViens" ("MaQuaTang" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Code" character varying(40) NOT NULL, "MaDonHang" integer NOT NULL, "MaKhoaHoc" integer NOT NULL, "MaNguoiTang" integer NOT NULL, "MaNguoiNhan" integer NULL, "TrangThai" character varying(30) NOT NULL, "CreatedAt" timestamp with time zone NOT NULL, "ActivatedAt" timestamp with time zone NULL, "RedeemedAt" timestamp with time zone NULL, "ExpiredAt" timestamp with time zone NULL);
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_MaQuaTangHocViens_Code" ON "MaQuaTangHocViens" ("Code");
            CREATE INDEX IF NOT EXISTS "IX_MaQuaTangHocViens_MaDonHang" ON "MaQuaTangHocViens" ("MaDonHang");
            CREATE INDEX IF NOT EXISTS "IX_MaQuaTangHocViens_MaKhoaHoc" ON "MaQuaTangHocViens" ("MaKhoaHoc");
            CREATE INDEX IF NOT EXISTS "IX_MaQuaTangHocViens_MaNguoiNhan" ON "MaQuaTangHocViens" ("MaNguoiNhan");
            CREATE INDEX IF NOT EXISTS "IX_MaQuaTangHocViens_MaNguoiTang_TrangThai_CreatedAt" ON "MaQuaTangHocViens" ("MaNguoiTang", "TrangThai", "CreatedAt");
            CREATE TABLE IF NOT EXISTS "MaGiamGiaKhoaHocs" ("MaLienKet" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "MaVoucher" integer NOT NULL, "MaKhoaHoc" integer NOT NULL);
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_MaQuaTangHocViens_DonHangKhoaHocs_MaDonHang') THEN
                    ALTER TABLE "MaQuaTangHocViens" ADD CONSTRAINT "FK_MaQuaTangHocViens_DonHangKhoaHocs_MaDonHang"
                        FOREIGN KEY ("MaDonHang") REFERENCES "DonHangKhoaHocs" ("MaDonHang") ON DELETE CASCADE;
                END IF;
            END
            $$;
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_MaGiamGiaKhoaHocs_MaVoucher_MaKhoaHoc" ON "MaGiamGiaKhoaHocs" ("MaVoucher", "MaKhoaHoc");
            CREATE INDEX IF NOT EXISTS "IX_MaGiamGiaKhoaHocs_MaKhoaHoc" ON "MaGiamGiaKhoaHocs" ("MaKhoaHoc");
            CREATE INDEX IF NOT EXISTS "IX_DonHangKhoaHocs_MaVoucher" ON "DonHangKhoaHocs" ("MaVoucher");
            CREATE INDEX IF NOT EXISTS "IX_MaGiamGias_MaNguoiTao" ON "MaGiamGias" ("MaNguoiTao");
            """);

        migrationBuilder.Sql("""
            ALTER TABLE "KhoaHocs" ADD COLUMN IF NOT EXISTS "DeletedAt" timestamp with time zone NULL;
            ALTER TABLE "KhoaHocs" ADD COLUMN IF NOT EXISTS "DeletedBy" integer NULL;
            ALTER TABLE "KhoaHocs" ADD COLUMN IF NOT EXISTS "DonViTienTe" character varying(10) NOT NULL DEFAULT 'VND';
            ALTER TABLE "KhoaHocs" ADD COLUMN IF NOT EXISTS "ChoPhepMua" boolean NOT NULL DEFAULT true;
            ALTER TABLE "KhoaHocs" ADD COLUMN IF NOT EXISTS "BanSeHocDuocGi" text NULL;
            ALTER TABLE "KeyAPIs" ADD COLUMN IF NOT EXISTS "DeletedAt" timestamp with time zone NULL;
            ALTER TABLE "KeyAPIs" ADD COLUMN IF NOT EXISTS "DeletedBy" integer NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "CoQuiz" boolean NOT NULL DEFAULT true;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "VideoPublicId" character varying(255) NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "VideoSource" character varying(20) NOT NULL DEFAULT 'youtube';
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "VideoStatus" character varying(30) NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "VideoDurationS" integer NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "VideoSizeMb" integer NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "HasSubtitle" boolean NOT NULL DEFAULT false;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "SubtitleUrl" text NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "SubtitleSource" character varying(20) NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "AiFeaturesEnabled" boolean NOT NULL DEFAULT true;
            CREATE TABLE IF NOT EXISTS "GiangVienQuotas" ("MaGiangVien" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "StorageUsedMb" bigint NOT NULL DEFAULT 0, "StorageLimitMb" bigint NOT NULL DEFAULT 51200, "AiBalanceUsd" numeric(10,4) NOT NULL DEFAULT 0, "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now());
            CREATE TABLE IF NOT EXISTS "AIBalanceHolds" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "MaGiangVien" integer NOT NULL, "MaBaiHoc" integer NOT NULL, "AmountUsd" numeric(10,4) NOT NULL, "Status" character varying(20) NOT NULL, "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(), "SettledAt" timestamp with time zone NULL);
            CREATE TABLE IF NOT EXISTS "WebhookLogs" ("NotificationId" character varying(128) PRIMARY KEY, "NotificationType" character varying(50) NOT NULL, "Payload" jsonb NOT NULL, "ProcessedAt" timestamp with time zone NOT NULL DEFAULT now());
            CREATE UNIQUE INDEX IF NOT EXISTS "UX_HoSoGV_Email_DangXuLy" ON "HoSoDangKyGiangViens" (lower("Email")) WHERE "TrangThaiHoSo" <> 'TuChoi';
            CREATE UNIQUE INDEX IF NOT EXISTS "UX_HoSoGV_TaiKhoan_DangXuLy" ON "HoSoDangKyGiangViens" (lower("TaiKhoan")) WHERE "TrangThaiHoSo" <> 'TuChoi';
            CREATE UNIQUE INDEX IF NOT EXISTS "UX_HoSoGV_SoGiayTo_DangXuLy" ON "HoSoDangKyGiangViens" ("SoGiayTo") WHERE "TrangThaiHoSo" <> 'TuChoi';
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder) { }
}
