// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using educodeai_server.Data;

#nullable disable

namespace educodeai_server.Migrations
{
    [DbContext(typeof(EduCodeAIDbContext))]
    partial class EduCodeAIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("educodeai_server.Models.BaiHocModel", b =>
                {
                    b.Property<int>("MaBaiHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiHoc"));

                    b.Property<string>("LinkVideo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiBaiHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaChuong")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiLuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaBaiHoc");

                    b.HasIndex("MaChuong");

                    b.ToTable("BaiHocs");
                });

            modelBuilder.Entity("educodeai_server.Models.BaiNopModel", b =>
                {
                    b.Property<int>("MaBaiNop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiNop"));

                    b.Property<int>("BoNhoSuDung")
                        .HasColumnType("int");

                    b.Property<string>("CodeNop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanNop")
                        .HasColumnType("int");

                    b.Property<int>("MaBaiTap")
                        .HasColumnType("int");

                    b.Property<int>("MaNgonNgu")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianChay")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBaiNop");

                    b.HasIndex("MaBaiTap");

                    b.HasIndex("MaNgonNgu");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("BaiNops");
                });

            modelBuilder.Entity("educodeai_server.Models.BaiTapModel", b =>
                {
                    b.Property<int>("MaBaiTap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiTap"));

                    b.Property<string>("DeBai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiHanBoNho")
                        .HasColumnType("int");

                    b.Property<int>("GioiHanThoiGian")
                        .HasColumnType("int");

                    b.Property<int>("MaBaiHoc")
                        .HasColumnType("int");

                    b.HasKey("MaBaiTap");

                    b.HasIndex("MaBaiHoc");

                    b.ToTable("BaiTaps");
                });

            modelBuilder.Entity("educodeai_server.Models.BaiTap_NgonNguModel", b =>
                {
                    b.Property<int>("MaBaiTapNgonNgu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiTapNgonNgu"));

                    b.Property<string>("CodeMau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBaiTap")
                        .HasColumnType("int");

                    b.Property<int>("MaNgonNgu")
                        .HasColumnType("int");

                    b.HasKey("MaBaiTapNgonNgu");

                    b.HasIndex("MaNgonNgu");

                    b.HasIndex("MaBaiTap", "MaNgonNgu")
                        .IsUnique();

                    b.ToTable("BaiTap_NgonNgus");
                });

            modelBuilder.Entity("educodeai_server.Models.BinhLuanModel", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"));

                    b.Property<int>("MaBaiHoc")
                        .HasColumnType("int");

                    b.Property<int?>("MaBinhLuanCha")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBinhLuan");

                    b.HasIndex("MaBaiHoc");

                    b.HasIndex("MaBinhLuanCha");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("educodeai_server.Models.BoThuNghiemModel", b =>
                {
                    b.Property<int>("MaBoThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBoThu"));

                    b.Property<bool>("AnDanh")
                        .HasColumnType("bit");

                    b.Property<string>("DauRaMongMuon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DauVao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBaiTap")
                        .HasColumnType("int");

                    b.HasKey("MaBoThu");

                    b.HasIndex("MaBaiTap");

                    b.ToTable("BoThuNghiems");
                });

            modelBuilder.Entity("educodeai_server.Models.ChuongHocModel", b =>
                {
                    b.Property<int>("MaChuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuong"));

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenChuong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaChuong");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("ChuongHocs");
                });

            modelBuilder.Entity("educodeai_server.Models.CuocHoiThoaiAIModel", b =>
                {
                    b.Property<int>("MaHoiThoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoiThoai"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaHoiThoai");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("CuocHoiThoaiAIs");
                });

            modelBuilder.Entity("educodeai_server.Models.DangKyKhoaHocModel", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("TienDo")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDangKy");

                    b.HasIndex("MaKhoaHoc");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DangKyKhoaHocs");
                });

            modelBuilder.Entity("educodeai_server.Models.DanhGiaModel", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaKhoaHoc");

                    b.HasIndex("MaNguoiDung", "MaKhoaHoc")
                        .IsUnique();

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("educodeai_server.Models.KhoaHocModel", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<double>("DiemDanhGiaTB")
                        .HasColumnType("float");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KyNangChinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LinhVuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThoiLuongGio")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhoaHoc");

                    b.HasIndex("MaGiangVien");

                    b.ToTable("KhoaHocs");
                });

            modelBuilder.Entity("educodeai_server.Models.LoTrinhAIModel", b =>
                {
                    b.Property<int>("MaLoTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoTrinh"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungJSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YeuCau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoTrinh");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LoTrinhAIs");
                });

            modelBuilder.Entity("educodeai_server.Models.NgonNguLapTrinhModel", b =>
                {
                    b.Property<int>("MaNgonNgu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNgonNgu"));

                    b.Property<string>("TenNgonNgu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNgonNgu");

                    b.ToTable("NgonNguLapTrinhs");
                });

            modelBuilder.Entity("educodeai_server.Models.NguoiDungModel", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("TaiKhoan")
                        .IsUnique();

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("educodeai_server.Models.TienDoBaiHocModel", b =>
                {
                    b.Property<int>("MaTienDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTienDo"));

                    b.Property<bool>("DaXem")
                        .HasColumnType("bit");

                    b.Property<int>("MaBaiHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianHoc")
                        .HasColumnType("int");

                    b.HasKey("MaTienDo");

                    b.HasIndex("MaBaiHoc");

                    b.HasIndex("MaNguoiDung", "MaBaiHoc")
                        .IsUnique();

                    b.ToTable("TienDoBaiHocs");
                });

            modelBuilder.Entity("educodeai_server.Models.TinNhanAIModel", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhan"));

                    b.Property<int>("MaHoiThoai")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaHoiThoai");

                    b.ToTable("TinNhanAIs");
                });

            modelBuilder.Entity("educodeai_server.Models.BaiHocModel", b =>
                {
                    b.HasOne("educodeai_server.Models.ChuongHocModel", "ChuongHoc")
                        .WithMany("BaiHocs")
                        .HasForeignKey("MaChuong")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChuongHoc");
                });

            modelBuilder.Entity("educodeai_server.Models.BaiNopModel", b =>
                {
                    b.HasOne("educodeai_server.Models.BaiTapModel", "BaiTap")
                        .WithMany("BaiNops")
                        .HasForeignKey("MaBaiTap")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("educodeai_server.Models.NgonNguLapTrinhModel", "NgonNgu")
                        .WithMany("BaiNops")
                        .HasForeignKey("MaNgonNgu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("educodeai_server.Models.NguoiDungModel", "NguoiDung")
                        .WithMany("BaiNops")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiTap");

                    b.Navigation("NgonNgu");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("educodeai_server.Models.BaiTapModel", b =>
                {
                    b.HasOne("educodeai_server.Models.BaiHocModel", "BaiHoc")
                        .WithMany("BaiTaps")
                        .HasForeignKey("MaBaiHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiHoc");
                });

            modelBuilder.Entity("educodeai_server.Models.BaiTap_NgonNguModel", b =>
                {
                    b.HasOne("educodeai_server.Models.BaiTapModel", "BaiTap")
                        .WithMany("BaiTap_NgonNgus")
                        .HasForeignKey("MaBaiTap")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("educodeai_server.Models.NgonNguLapTrinhModel", "NgonNgu")
                        .WithMany("BaiTap_NgonNgus")
                        .HasForeignKey("MaNgonNgu")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiTap");

                    b.Navigation("NgonNgu");
                });

            modelBuilder.Entity("educodeai_server.Models.BinhLuanModel", b =>
                {
                    b.HasOne("educodeai_server.Models.BaiHocModel", "BaiHoc")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaBaiHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("educodeai_server.Models.BinhLuanModel", "BinhLuanCha")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaBinhLuanCha")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("educodeai_server.Models.NguoiDungModel", "NguoiDung")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("BinhLuanCha");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("educodeai_server.Models.BoThuNghiemModel", b =>
                {
                    b.HasOne("educodeai_server.Models.BaiTapModel", "BaiTap")
                        .WithMany("BoThuNghiems")
                        .HasForeignKey("MaBaiTap")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiTap");
                });

            modelBuilder.Entity("educodeai_server.Models.ChuongHocModel", b =>
                {
                    b.HasOne("educodeai_server.Models.KhoaHocModel", "KhoaHoc")
                        .WithMany("ChuongHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("educodeai_server.Models.CuocHoiThoaiAIModel", b =>
                {
                    b.HasOne("educodeai_server.Models.NguoiDungModel", "NguoiDung")
                        .WithMany("CuocHoiThoaiAIs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("educodeai_server.Models.DangKyKhoaHocModel", b =>
                {
                    b.HasOne("educodeai_server.Models.KhoaHocModel", "KhoaHoc")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("educodeai_server.Models.NguoiDungModel", "NguoiDung")
                        .WithMany("DangKyKhoaHocs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("educodeai_server.Models.DanhGiaModel", b =>
                {
                    b.HasOne("educodeai_server.Models.KhoaHocModel", "KhoaHoc")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("educodeai_server.Models.NguoiDungModel", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("educodeai_server.Models.KhoaHocModel", b =>
                {
                    b.HasOne("educodeai_server.Models.NguoiDungModel", "GiangVien")
                        .WithMany("KhoaHocs")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiangVien");
                });

            modelBuilder.Entity("educodeai_server.Models.LoTrinhAIModel", b =>
                {
                    b.HasOne("educodeai_server.Models.NguoiDungModel", "NguoiDung")
                        .WithMany("LoTrinhAIs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("educodeai_server.Models.TienDoBaiHocModel", b =>
                {
                    b.HasOne("educodeai_server.Models.BaiHocModel", "BaiHoc")
                        .WithMany("TienDoBaiHocs")
                        .HasForeignKey("MaBaiHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("educodeai_server.Models.NguoiDungModel", "NguoiDung")
                        .WithMany("TienDoBaiHocs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaiHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("educodeai_server.Models.TinNhanAIModel", b =>
                {
                    b.HasOne("educodeai_server.Models.CuocHoiThoaiAIModel", "CuocHoiThoaiAI")
                        .WithMany("TinNhanAIs")
                        .HasForeignKey("MaHoiThoai")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CuocHoiThoaiAI");
                });

            modelBuilder.Entity("educodeai_server.Models.BaiHocModel", b =>
                {
                    b.Navigation("BaiTaps");

                    b.Navigation("BinhLuans");

                    b.Navigation("TienDoBaiHocs");
                });

            modelBuilder.Entity("educodeai_server.Models.BaiTapModel", b =>
                {
                    b.Navigation("BaiNops");

                    b.Navigation("BaiTap_NgonNgus");

                    b.Navigation("BoThuNghiems");
                });

            modelBuilder.Entity("educodeai_server.Models.BinhLuanModel", b =>
                {
                    b.Navigation("BinhLuans");
                });

            modelBuilder.Entity("educodeai_server.Models.ChuongHocModel", b =>
                {
                    b.Navigation("BaiHocs");
                });

            modelBuilder.Entity("educodeai_server.Models.CuocHoiThoaiAIModel", b =>
                {
                    b.Navigation("TinNhanAIs");
                });

            modelBuilder.Entity("educodeai_server.Models.KhoaHocModel", b =>
                {
                    b.Navigation("ChuongHocs");

                    b.Navigation("DangKyKhoaHocs");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("educodeai_server.Models.NgonNguLapTrinhModel", b =>
                {
                    b.Navigation("BaiNops");

                    b.Navigation("BaiTap_NgonNgus");
                });

            modelBuilder.Entity("educodeai_server.Models.NguoiDungModel", b =>
                {
                    b.Navigation("BaiNops");

                    b.Navigation("BinhLuans");

                    b.Navigation("CuocHoiThoaiAIs");

                    b.Navigation("DangKyKhoaHocs");

                    b.Navigation("DanhGias");

                    b.Navigation("KhoaHocs");

                    b.Navigation("LoTrinhAIs");

                    b.Navigation("TienDoBaiHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
