import { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuth } from '../../auth/hooks/use-auth';
import { CourseLearningService } from '../services/course-learning.service';
import type { Lesson, Note } from '../types/learning.types';

export function LessonTools({ lesson }: { lesson: Lesson }) {
  const { session } = useAuth(); const user = session?.user; const [visible, setVisible] = useState(false); const [note, setNote] = useState(''); const [notes, setNotes] = useState<Note[]>([]); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const loadNotes = async () => { if (!user?.maNguoiDung) return; setLoading(true); setMessage(''); try { setNotes(await CourseLearningService.getNotes(lesson.id, user.maNguoiDung)); } catch { setMessage('Không thể tải ghi chú.'); } finally { setLoading(false); } };
  useEffect(() => { if (visible) void loadNotes(); }, [visible, lesson.id, user?.maNguoiDung]);
  const saveNote = async () => { if (!user?.maNguoiDung || !note.trim() || saving) return; setSaving(true); setMessage(''); try { await CourseLearningService.saveNote({ MaBaiHoc: lesson.id, MaNguoiDung: user.maNguoiDung, ThoiGianVideo: 0, NoiDung: note.trim() }); setNote(''); setMessage('Đã lưu ghi chú.'); await loadNotes(); } catch { setMessage('Không thể lưu ghi chú. Nội dung vẫn được giữ lại.'); } finally { setSaving(false); } };
  return <><Pressable style={styles.toolCard} onPress={() => setVisible(true)}><Text style={styles.toolIcon}>✎</Text><View style={styles.toolMain}><Text style={styles.title}>Ghi chú bài học</Text><Text style={styles.muted}>{notes.length ? `${notes.length} ghi chú đã lưu` : 'Lưu ý quan trọng khi học'}</Text></View><Text style={styles.open}>Mở</Text></Pressable><Modal visible={visible} animationType="slide" transparent onRequestClose={() => setVisible(false)}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.sheetHeader}><Text style={styles.sheetTitle}>Ghi chú bài học</Text><Pressable onPress={() => setVisible(false)} style={styles.close}><Text style={styles.closeText}>Đóng</Text></Pressable></View>{loading ? <ActivityIndicator color="#f69050" /> : notes.slice(0, 3).map((item) => <View key={item.id} style={styles.note}><Text style={styles.noteText}>{item.noiDung}</Text><Text style={styles.noteDate}>{item.ngayTao ? new Date(item.ngayTao).toLocaleDateString('vi-VN') : ''}</Text></View>)}{!loading && !notes.length && <Text style={styles.muted}>Chưa có ghi chú cho bài học này.</Text>}<TextInput value={note} onChangeText={setNote} multiline placeholder="Viết ghi chú của bạn..." placeholderTextColor="#9ca3af" style={styles.input} /><Pressable disabled={saving || !note.trim()} onPress={() => void saveNote()} style={[styles.button, (saving || !note.trim()) && styles.disabled]}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Lưu ghi chú</Text>}</Pressable>{!!message && <Text style={styles.message}>{message}</Text>}</View></View></Modal></>;
}
const styles = StyleSheet.create({ toolCard: { minHeight: 62, marginTop: 10, padding: 12, flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 12 }, toolIcon: { color: '#f69050', fontSize: 23, width: 34, textAlign: 'center' }, toolMain: { flex: 1, marginLeft: 8 }, title: { color: '#111827', fontWeight: '800' }, muted: { color: '#6b7280', lineHeight: 20, marginTop: 3 }, open: { color: '#f69050', fontWeight: '700' }, backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(17,24,39,.45)' }, sheet: { backgroundColor: '#f9fafb', borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: 18, maxHeight: '82%' }, sheetHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 }, sheetTitle: { color: '#111827', fontSize: 20, fontWeight: '800' }, close: { marginLeft: 'auto', minHeight: 44, justifyContent: 'center' }, closeText: { color: '#f69050', fontWeight: '700' }, note: { backgroundColor: '#fff', padding: 12, borderRadius: 10, marginBottom: 8, borderWidth: 1, borderColor: '#e5e7eb' }, noteText: { color: '#374151', lineHeight: 21 }, noteDate: { color: '#9ca3af', fontSize: 12, marginTop: 5 }, input: { minHeight: 90, padding: 12, color: '#111827', backgroundColor: '#fff', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 10, textAlignVertical: 'top', marginTop: 10 }, button: { minHeight: 46, marginTop: 12, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#f69050' }, buttonText: { color: '#fff', fontWeight: '700' }, disabled: { opacity: .5 }, message: { color: '#6b7280', marginTop: 8 } });
