import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { CourseLearningService } from '../services/course-learning.service';
import type { Lesson, QuizAnswer } from '../types/learning.types';

type Question = { id: number; text: string; options: string[]; correctIndex: number };
function parseQuestions(json?: string): Question[] { try { const parsed = JSON.parse(json || '[]'); const source = Array.isArray(parsed) ? parsed : parsed?.['Câu hỏi'] ?? []; return source.map((item: Record<string, unknown>, index: number) => { const options = Array.isArray(item.LuaChon) ? item.LuaChon : [item.dapAnA, item.dapAnB, item.dapAnC, item.dapAnD]; const answer = String(item.dapAnDung ?? item.DapAnDung ?? '').trim().toUpperCase(); const letters: Record<string, number> = { A: 0, B: 1, C: 2, D: 3 }; const numeric = Number(answer); return { id: Number(item.id ?? item.Id ?? index + 1), text: String(item.cauHoi ?? item.NoiDung ?? ''), options: [0, 1, 2, 3].map((i) => String(options[i] ?? '')).filter(Boolean), correctIndex: answer in letters ? letters[answer] : Number.isInteger(numeric) && numeric >= 0 && numeric <= 3 ? numeric : 0 }; }); } catch { return []; } }

export function QuizPanel({ lesson, userId }: { lesson: Lesson; userId?: number }) {
  const questions = useMemo(() => parseQuestions(lesson.thongTinQuiz?.duLieuCauHoiJSON), [lesson.thongTinQuiz?.duLieuCauHoiJSON]);
  const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Record<number, number>>({}); const [submitting, setSubmitting] = useState(false); const [result, setResult] = useState<{ correct: number; total: number; passed: boolean } | null>(null); const [message, setMessage] = useState('');
  const question = questions[index];
  const submit = async () => { if (!userId || !lesson.thongTinQuiz || submitting || !questions.length) return; setSubmitting(true); setMessage(''); const detail: QuizAnswer[] = questions.flatMap((item, itemIndex) => answers[itemIndex] === undefined ? [] : [{ IdCauHoi: item.id, IndexLuaChon: answers[itemIndex] }]); const correct = questions.reduce((total, item, itemIndex) => total + (answers[itemIndex] === item.correctIndex ? 1 : 0), 0); const score = correct / questions.length * 100; try { await CourseLearningService.saveQuizResult({ MaBaiHoc: lesson.id, MaBaiTap: lesson.thongTinQuiz.maBaiTap, MaNguoiDung: userId, DiemSo: score, SoCauDung: correct, TongSoCau: questions.length, DaDat: score >= lesson.thongTinQuiz.diemCanDat, ChiTietLamBai: detail }); setResult({ correct, total: questions.length, passed: score >= lesson.thongTinQuiz.diemCanDat }); } catch { setMessage('Không thể nộp bài, vui lòng thử lại.'); } finally { setSubmitting(false); } };
  const retry = () => { setAnswers({}); setIndex(0); setResult(null); setMessage(''); };
  if (!questions.length) return <View style={styles.empty}><Text style={styles.muted}>Chưa có dữ liệu câu hỏi.</Text></View>;
  if (result) return <View style={styles.resultCard}><Text style={styles.resultTitle}>{result.passed ? 'Chúc mừng, bạn đã đạt!' : 'Bạn chưa đạt yêu cầu'}</Text><Text style={styles.resultScore}>{result.correct}/{result.total} câu đúng</Text><Text style={styles.muted}>Điểm đạt yêu cầu: {lesson.thongTinQuiz?.diemCanDat}%</Text>{lesson.thongTinQuiz?.choPhepLamLai && <Pressable style={styles.secondary} onPress={retry}><Text style={styles.secondaryText}>Làm lại bài</Text></Pressable>}</View>;
  return <View style={styles.container}><View style={styles.quizHeader}><Text style={styles.label}>TRẮC NGHIỆM KIẾN THỨC</Text><Text style={styles.counter}>Câu {index + 1}/{questions.length}</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${((index + 1) / questions.length) * 100}%` }]} /></View><Text style={styles.question}>{question.text}</Text>{question.options.map((option, optionIndex) => <Pressable key={optionIndex} style={[styles.option, answers[index] === optionIndex && styles.selected]} onPress={() => setAnswers((value) => ({ ...value, [index]: optionIndex }))}><View style={[styles.radio, answers[index] === optionIndex && styles.radioSelected]} /><Text style={styles.optionText}>{option}</Text></Pressable>)}<View style={styles.actions}>{index > 0 && <Pressable style={styles.secondary} onPress={() => setIndex((value) => value - 1)}><Text style={styles.secondaryText}>Quay lại</Text></Pressable>}{index < questions.length - 1 ? <Pressable style={styles.primary} onPress={() => setIndex((value) => value + 1)}><Text style={styles.primaryText}>Tiếp theo</Text></Pressable> : <Pressable style={[styles.primary, (submitting || answers[index] === undefined) && styles.disabled]} disabled={submitting || answers[index] === undefined} onPress={() => void submit()}>{submitting ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryText}>Nộp bài</Text>}</Pressable>}</View>{!!message && <Text style={styles.error}>{message}</Text>}</View>;
}
const styles = StyleSheet.create({ container: { marginTop: 4, backgroundColor: '#fff', borderRadius: 16, padding: 18, borderWidth: 1, borderColor: '#e5e7eb' }, quizHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, label: { color: '#f69050', fontSize: 12, fontWeight: '800', letterSpacing: .6 }, counter: { color: '#6b7280', fontSize: 13, fontWeight: '700' }, track: { height: 5, backgroundColor: '#f3f4f6', borderRadius: 4, overflow: 'hidden', marginTop: 12 }, fill: { height: '100%', backgroundColor: '#f69050' }, question: { color: '#111827', fontSize: 19, lineHeight: 27, fontWeight: '800', marginTop: 22, marginBottom: 12 }, option: { minHeight: 54, padding: 13, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 11, marginTop: 9 }, selected: { borderColor: '#f69050', backgroundColor: '#fff5eb' }, radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#d1d5db', marginRight: 10 }, radioSelected: { borderColor: '#f69050', backgroundColor: '#f69050' }, optionText: { flex: 1, color: '#374151', lineHeight: 21 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 9, marginTop: 18 }, primary: { minHeight: 46, minWidth: 110, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#f69050' }, primaryText: { color: '#fff', fontWeight: '700' }, secondary: { minHeight: 46, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#fff5eb' }, secondaryText: { color: '#d97706', fontWeight: '700' }, disabled: { opacity: .5 }, error: { color: '#dc2626', marginTop: 10 }, empty: { padding: 18 }, muted: { color: '#6b7280', lineHeight: 21 }, resultCard: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#e5e7eb', padding: 22, alignItems: 'center' }, resultTitle: { color: '#111827', fontSize: 20, fontWeight: '800', textAlign: 'center' }, resultScore: { color: '#f69050', fontSize: 32, fontWeight: '800', marginTop: 12, marginBottom: 4 } });
