import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { CourseLearningService } from '../services/course-learning.service';
import type { Lesson, QuizAnswer } from '../types/learning.types';

type Question = { id: number; text: string; options: string[]; correctIndex: number };
function parseQuestions(json?: string): Question[] { try { const parsed = JSON.parse(json || '[]'); const source = Array.isArray(parsed) ? parsed : parsed?.['Câu hỏi'] ?? []; return source.map((item: Record<string, unknown>, index: number) => { const options = Array.isArray(item.LuaChon) ? item.LuaChon : [item.dapAnA, item.dapAnB, item.dapAnC, item.dapAnD]; const answer = String(item.dapAnDung ?? item.DapAnDung ?? '').trim().toUpperCase(); const letters: Record<string, number> = { A: 0, B: 1, C: 2, D: 3 }; const numeric = Number(answer); return { id: Number(item.id ?? item.Id ?? index + 1), text: String(item.cauHoi ?? item.NoiDung ?? ''), options: [0, 1, 2, 3].map((i) => String(options[i] ?? '')).filter(Boolean), correctIndex: answer in letters ? letters[answer] : Number.isInteger(numeric) && numeric >= 0 && numeric <= 3 ? numeric : -1 }; }); } catch { return []; } }

export function QuizPanel({ lesson, userId, onPassed }: { lesson: Lesson; userId?: number; onPassed?: () => void }) {
  const parsedQuestions = useMemo(() => parseQuestions(lesson.thongTinQuiz?.duLieuCauHoiJSON), [lesson.thongTinQuiz?.duLieuCauHoiJSON]);
  const questions = useMemo(() => { if (!lesson.thongTinQuiz?.daoCauHoi) return parsedQuestions; const shuffled = [...parsedQuestions]; for (let i = shuffled.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]; } return shuffled; }, [parsedQuestions, lesson.thongTinQuiz?.daoCauHoi]);
  const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Record<number, number>>({}); const [submitting, setSubmitting] = useState(false); const [result, setResult] = useState<{ correct: number; total: number; passed: boolean } | null>(null); const [message, setMessage] = useState('');
  const [timeLeft, setTimeLeft] = useState<number | null>(lesson.thongTinQuiz?.thoiGianLamBai ?? null);
  const question = questions[index];
  const submit = async () => { if (!userId || !lesson.thongTinQuiz || submitting || !questions.length || Object.keys(answers).length < questions.length) return; setSubmitting(true); setMessage(''); const detail: QuizAnswer[] = questions.map((item, itemIndex) => ({ IdCauHoi: item.id, IndexLuaChon: answers[itemIndex] })); const correct = questions.reduce((total, item, itemIndex) => total + (answers[itemIndex] === item.correctIndex ? 1 : 0), 0); const score = correct / questions.length * 100; try { const saved = await CourseLearningService.saveQuizResult({ MaBaiHoc: lesson.id, MaBaiTap: lesson.thongTinQuiz.maBaiTap, MaNguoiDung: userId, DiemSo: score, SoCauDung: correct, TongSoCau: questions.length, DaDat: score >= lesson.thongTinQuiz.diemCanDat, ChiTietLamBai: detail }); if (!saved) throw new Error('save failed'); const passed = score >= lesson.thongTinQuiz.diemCanDat; setResult({ correct, total: questions.length, passed }); if (passed) onPassed?.(); } catch { setMessage('Không thể nộp bài, vui lòng thử lại.'); } finally { setSubmitting(false); } };
  useEffect(() => { if (timeLeft === null || result || timeLeft <= 0) return; const timer = setInterval(() => setTimeLeft((value) => value === null ? null : Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [timeLeft, result]);
  useEffect(() => { if (timeLeft === 0 && !result && !submitting && Object.keys(answers).length === questions.length) void submit(); }, [timeLeft, result, submitting, answers, questions.length]);
  const retry = () => { setAnswers({}); setIndex(0); setResult(null); setMessage(''); setTimeLeft(lesson.thongTinQuiz?.thoiGianLamBai ?? null); };
  if (!questions.length) return <View style={styles.empty}><Text style={styles.muted}>Chưa có dữ liệu câu hỏi.</Text></View>;
  if (result) return <View style={styles.resultCard}><Text style={styles.resultTitle}>{result.passed ? 'Chúc mừng, bạn đã đạt!' : 'Bạn chưa đạt yêu cầu'}</Text><Text style={styles.resultScore}>{result.correct}/{result.total} câu đúng</Text>{lesson.thongTinQuiz?.choPhepLamLai && <Pressable style={styles.secondary} onPress={retry}><Text style={styles.secondaryText}>Làm lại bài</Text></Pressable>}</View>;
  return <View style={styles.container}><View style={styles.quizHeader}><Text style={styles.label}>TRẮC NGHIỆM KIẾN THỨC</Text><Text style={styles.counter}>Câu {index + 1}/{questions.length}{timeLeft !== null ? ` · ${Math.floor(timeLeft / 60)}:${String(timeLeft % 60).padStart(2, '0')}` : ''}</Text></View><Text style={styles.question}>{question.text}</Text>{question.options.map((option, optionIndex) => <Pressable key={optionIndex} style={[styles.option, answers[index] === optionIndex && styles.selected]} onPress={() => setAnswers((value) => ({ ...value, [index]: optionIndex }))}><Text style={styles.optionText}>{option}</Text></Pressable>)}<View style={styles.actions}>{index > 0 && <Pressable style={styles.secondary} onPress={() => setIndex((value) => value - 1)}><Text style={styles.secondaryText}>Quay lại</Text></Pressable>}{index < questions.length - 1 ? <Pressable style={styles.primary} onPress={() => setIndex((value) => value + 1)}><Text style={styles.primaryText}>Tiếp theo</Text></Pressable> : <Pressable style={[styles.primary, (submitting || Object.keys(answers).length < questions.length) && styles.disabled]} disabled={submitting || Object.keys(answers).length < questions.length} onPress={() => void submit()}>{submitting ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryText}>Nộp bài</Text>}</Pressable>}</View>{!!message && <Text style={styles.error}>{message}</Text>}</View>;
}
const styles = StyleSheet.create({ container: { marginTop: 4, backgroundColor: '#fff', borderRadius: 16, padding: 18, borderWidth: 1, borderColor: '#e5e7eb' }, quizHeader: { flexDirection: 'row', justifyContent: 'space-between' }, label: { color: '#f69050', fontSize: 12, fontWeight: '800' }, counter: { color: '#6b7280', fontSize: 13 }, question: { color: '#111827', fontSize: 19, fontWeight: '800', marginTop: 22 }, option: { minHeight: 54, padding: 13, borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 11, marginTop: 9 }, selected: { borderColor: '#f69050', backgroundColor: '#fff5eb' }, optionText: { color: '#374151' }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 9, marginTop: 18 }, primary: { minHeight: 46, paddingHorizontal: 16, justifyContent: 'center', borderRadius: 10, backgroundColor: '#f69050' }, primaryText: { color: '#fff', fontWeight: '700' }, secondary: { minHeight: 46, paddingHorizontal: 16, justifyContent: 'center', borderRadius: 10, backgroundColor: '#fff5eb' }, secondaryText: { color: '#d97706', fontWeight: '700' }, disabled: { opacity: .5 }, error: { color: '#dc2626', marginTop: 10 }, empty: { padding: 18 }, muted: { color: '#6b7280' }, resultCard: { padding: 22, alignItems: 'center' }, resultTitle: { color: '#111827', fontSize: 20, fontWeight: '800' }, resultScore: { color: '#f69050', fontSize: 32, fontWeight: '800', margin: 12 } });
