import { useState } from 'react';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { CourseLearningService } from '../services/course-learning.service';
import type { ReviewSummary } from '../types/learning.types';

export function ReviewPanel({ courseId, userId, canReview = true }: { courseId: number; userId?: number; canReview?: boolean }) {
  const [visible, setVisible] = useState(false); const [stars, setStars] = useState(0); const [comment, setComment] = useState(''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [summary, setSummary] = useState<ReviewSummary | null>(null);
  const load = async () => { try { setSummary(await CourseLearningService.getReviews(courseId)); } catch { setMessage('Không thể tải đánh giá.'); } };
  const open = () => { if (!canReview) return; setVisible(true); void load(); };
  const submit = async () => { if (!userId || !stars || saving) return; setSaving(true); setMessage(''); try { await CourseLearningService.addReview({ MaKhoaHoc: courseId, MaNguoiDung: userId, SoSao: stars, NhanXet: comment.trim() }); setMessage('Đã gửi đánh giá.'); setComment(''); await load(); } catch { setMessage('Không thể gửi đánh giá. Vui lòng thử lại.'); } finally { setSaving(false); } };
  return <><Pressable style={[styles.toolCard, !canReview && styles.disabledCard]} onPress={open} disabled={!canReview}><Text style={[styles.icon, !canReview && styles.disabledText]}>★</Text><View style={styles.main}><Text style={styles.title}>Đánh giá khóa học</Text><Text style={styles.muted}>{canReview ? (summary?.trungBinhSao ? `★ ${summary.trungBinhSao.toFixed(1)} · ${summary.tongSoDanhGia ?? 0} đánh giá` : 'Chia sẻ trải nghiệm học tập') : 'Hoàn thành khóa học để viết đánh giá'}</Text></View><Text style={[styles.open, !canReview && styles.disabledText]}>{canReview ? 'Xem' : 'Khóa'}</Text></Pressable><Modal visible={visible} animationType="slide" transparent onRequestClose={() => setVisible(false)}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.header}><Text style={styles.sheetTitle}>Đánh giá khóa học</Text><Pressable style={styles.close} onPress={() => setVisible(false)}><Text style={styles.open}>Đóng</Text></Pressable></View>{summary?.trungBinhSao !== undefined && <Text style={styles.summary}>★ {summary.trungBinhSao.toFixed(1)} / 5 · {summary.tongSoDanhGia ?? 0} đánh giá</Text>}<Text style={styles.label}>Đánh giá của bạn</Text><View style={styles.stars}>{[1,2,3,4,5].map((star) => <Pressable key={star} accessibilityLabel={`${star} sao`} onPress={() => setStars(star)}><Text style={[styles.star, star <= stars && styles.active]}>★</Text></Pressable>)}</View><TextInput value={comment} onChangeText={setComment} placeholder="Nhận xét của bạn..." placeholderTextColor="#9ca3af" style={styles.input} multiline /><Pressable disabled={!stars || saving} style={[styles.button, (!stars || saving) && styles.disabled]} onPress={() => void submit()}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Gửi đánh giá</Text>}</Pressable>{!!message && <Text style={styles.message}>{message}</Text>}</View></View></Modal></>;
}
const styles = StyleSheet.create({ toolCard: { minHeight: 62, marginTop: 10, padding: 12, flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 12 }, disabledCard: { opacity: .6, backgroundColor: '#f3f4f6' }, icon: { color: '#f59e0b', fontSize: 23, width: 34, textAlign: 'center' }, disabledText: { color: '#9ca3af' }, main: { flex: 1, marginLeft: 8 }, title: { color: '#111827', fontWeight: '800' }, muted: { color: '#6b7280', marginTop: 3 }, open: { color: '#f69050', fontWeight: '700' }, backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(17,24,39,.45)' }, sheet: { backgroundColor: '#f9fafb', borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: 18 }, header: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 }, sheetTitle: { color: '#111827', fontSize: 20, fontWeight: '800' }, close: { marginLeft: 'auto', minHeight: 44, justifyContent: 'center' }, summary: { color: '#d97706', fontWeight: '800', fontSize: 17, marginBottom: 18 }, label: { color: '#374151', fontWeight: '700' }, stars: { flexDirection: 'row', marginVertical: 10 }, star: { fontSize: 32, color: '#d1d5db', marginRight: 6 }, active: { color: '#f59e0b' }, input: { minHeight: 78, borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 10, padding: 12, backgroundColor: '#fff', textAlignVertical: 'top' }, button: { minHeight: 46, marginTop: 12, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#f69050' }, buttonText: { color: '#fff', fontWeight: '700' }, disabled: { opacity: .5 }, message: { color: '#6b7280', marginTop: 8 } });
