import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { CourseLearningService } from '../services/course-learning.service';

export function ReviewPanel({ courseId, userId }: { courseId: number; userId?: number }) {
  const [stars, setStars] = useState(0); const [comment, setComment] = useState(''); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const submit = async () => { if (!userId || !stars || saving) return; setSaving(true); setMessage(''); try { await CourseLearningService.addReview({ MaKhoaHoc: courseId, MaNguoiDung: userId, SoSao: stars, NhanXet: comment.trim() }); setMessage('Đã gửi đánh giá.'); } catch { setMessage('Không thể gửi đánh giá. Vui lòng thử lại.'); } finally { setSaving(false); } };
  return <View style={styles.container}><Text style={styles.title}>Đánh giá khóa học</Text><View style={styles.stars}>{[1,2,3,4,5].map((star) => <Pressable key={star} accessibilityLabel={`${star} sao`} onPress={() => setStars(star)}><Text style={[styles.star, star <= stars && styles.active]}>★</Text></Pressable>)}</View><TextInput value={comment} onChangeText={setComment} placeholder="Nhận xét của bạn..." placeholderTextColor="#9ca3af" style={styles.input} multiline /><Pressable disabled={!stars || saving} style={[styles.button, (!stars || saving) && styles.disabled]} onPress={() => void submit()}>{saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>Gửi đánh giá</Text>}</Pressable>{!!message && <Text style={styles.message}>{message}</Text>}</View>;
}
const styles = StyleSheet.create({ container: { marginTop: 24, padding: 16, backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#e5e7eb' }, title: { fontSize: 17, fontWeight: '800', color: '#111827' }, stars: { flexDirection: 'row', marginVertical: 12 }, star: { fontSize: 32, color: '#d1d5db', marginRight: 6 }, active: { color: '#f59e0b' }, input: { minHeight: 72, borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 10, padding: 12, textAlignVertical: 'top' }, button: { minHeight: 44, marginTop: 12, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: '#f69050' }, buttonText: { color: '#fff', fontWeight: '700' }, disabled: { opacity: 0.5 }, message: { color: '#6b7280', marginTop: 8 } });
