import { useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import Markdown from 'react-native-markdown-display';
import { getVideoSummary } from '../services/video-summary.service';
import type { Lesson } from '../types/learning.types';

export function VideoSummaryPanel({ lesson }: { lesson: Lesson }) {
  const [summary, setSummary] = useState(''); const [loading, setLoading] = useState(false); const [expanded, setExpanded] = useState(false); const [error, setError] = useState('');
  const storageKey = `ai_summary_lesson_${lesson.id}`;
  useEffect(() => { let active = true; setSummary(''); setLoading(false); setExpanded(false); setError(''); void AsyncStorage.getItem(storageKey).then((cached) => { if (active && cached) { setSummary(cached); setExpanded(false); } }); return () => { active = false; }; }, [storageKey, lesson.id]);
  const load = async () => { if (loading) return; setLoading(true); setError(''); try { const result = await getVideoSummary(lesson); if (!result) throw new Error('AI không trả về nội dung tóm tắt.'); setSummary(result); await AsyncStorage.setItem(storageKey, result); setExpanded(true); } catch (requestError: any) { const status = requestError?.response?.status; const raw = requestError?.response?.data; const detail = typeof raw === 'string' ? raw : raw?.message || raw?.thongBao; setError(detail ? `${detail}${status ? ` (${status})` : ''}` : 'Không thể tạo tóm tắt AI.'); } finally { setLoading(false); } };
  return <View style={styles.container}><View style={styles.header}><View><Text style={styles.title}>✦ Tài liệu & Tóm tắt AI</Text><Text style={styles.subtitle}>{summary ? 'Bản tóm tắt đầy đủ nội dung video' : 'Tạo tài liệu học tập từ video'}</Text></View>{summary ? <Pressable style={styles.actionButton} onPress={() => setExpanded((value) => !value)}><Text style={styles.action}>{expanded ? 'Thu gọn' : 'Xem'}</Text></Pressable> : <Pressable style={styles.actionButton} onPress={() => void load()} disabled={loading}><Text style={styles.action}>{loading ? 'Đang tạo...' : 'Tóm tắt'}</Text></Pressable>}</View>{loading && <View style={styles.loading}><ActivityIndicator color="#8b5cf6" /><Text style={styles.muted}>EduCode AI đang phân tích video...</Text></View>}{!!error && <View><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Thử lại</Text></Pressable></View>}{expanded && !!summary && <ScrollView style={styles.result}><Markdown style={markdownStyles}>{summary}</Markdown></ScrollView>}</View>;
}
const markdownStyles = { body: { color: '#1f2937', fontSize: 15, lineHeight: 24 }, heading1: { color: '#111827', fontSize: 21, fontWeight: '800' as const, marginTop: 8, marginBottom: 8 }, heading2: { color: '#111827', fontSize: 18, fontWeight: '800' as const, marginTop: 8, marginBottom: 6 }, heading3: { color: '#111827', fontSize: 16, fontWeight: '800' as const, marginTop: 6, marginBottom: 5 }, paragraph: { marginTop: 4, marginBottom: 8 }, bullet_list: { marginTop: 4, marginBottom: 6 }, code_inline: { backgroundColor: '#f1f5f9', color: '#be123c', borderRadius: 4, paddingHorizontal: 4 }, fence: { backgroundColor: '#111827', color: '#f9fafb', borderRadius: 8, padding: 12 } };
const styles = StyleSheet.create({ container: { marginTop: 14, padding: 14, backgroundColor: '#f3effe', borderRadius: 14 }, header: { minHeight: 50, flexDirection: 'row', alignItems: 'center' }, title: { color: '#4c1d95', fontSize: 16, fontWeight: '800' }, subtitle: { color: '#6b7280', fontSize: 12, marginTop: 3 }, action: { color: '#7c3aed', fontWeight: '800' }, actionButton: { marginLeft: 'auto', minHeight: 44, minWidth: 78, alignItems: 'flex-end', justifyContent: 'center' }, loading: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 12 }, muted: { color: '#6b7280' }, error: { color: '#b91c1c', lineHeight: 20, marginTop: 8 }, retry: { color: '#7c3aed', fontWeight: '800', marginTop: 8 }, result: { maxHeight: 500, marginTop: 10, padding: 14, paddingBottom: 24, backgroundColor: '#fff', borderRadius: 10 }, summary: { color: '#1f2937', fontSize: 15, lineHeight: 24 } });
