using educodeai_server.Data;
using Microsoft.EntityFrameworkCore;

namespace educodeai_server.Helpers;

/// <summary>
/// Bổ sung cột thiếu khi DB Supabase lệch so với EF model (migration đã ghi nhưng schema chưa đủ).
/// </summary>
public static class DatabaseSchemaSync
{
    public static async Task ApplyAsync(EduCodeAIDbContext context, CancellationToken cancellationToken = default)
    {
        await context.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "KhoaHocs" ADD COLUMN IF NOT EXISTS "DeletedAt" timestamp with time zone NULL;
            ALTER TABLE "KhoaHocs" ADD COLUMN IF NOT EXISTS "DeletedBy" integer NULL;
            ALTER TABLE "KhoaHocs" ADD COLUMN IF NOT EXISTS "DonViTienTe" character varying(10) NOT NULL DEFAULT 'VND';
            ALTER TABLE "KhoaHocs" ADD COLUMN IF NOT EXISTS "ChoPhepMua" boolean NOT NULL DEFAULT true;
            ALTER TABLE "KhoaHocs" ADD COLUMN IF NOT EXISTS "BanSeHocDuocGi" text NULL;

            ALTER TABLE "KeyAPIs" ADD COLUMN IF NOT EXISTS "DeletedAt" timestamp with time zone NULL;
            ALTER TABLE "KeyAPIs" ADD COLUMN IF NOT EXISTS "DeletedBy" integer NULL;

            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "CoQuiz" boolean NOT NULL DEFAULT true;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "VideoPublicId" character varying(255) NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "VideoSource" character varying(20) NOT NULL DEFAULT 'youtube';
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "VideoStatus" character varying(30) NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "VideoDurationS" integer NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "VideoSizeMb" integer NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "HasSubtitle" boolean NOT NULL DEFAULT false;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "SubtitleUrl" text NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "SubtitleSource" character varying(20) NULL;
            ALTER TABLE "BaiHocs" ADD COLUMN IF NOT EXISTS "AiFeaturesEnabled" boolean NOT NULL DEFAULT true;

            -- Bảng phụ trợ phase upload video cloud. Các DB restore từ backup (không qua
            -- EF migration) sẽ thiếu 3 bảng này -> tạo idempotent để tránh lỗi 500 khi
            -- lưu webhook / hold số dư / quota giảng viên.
            CREATE TABLE IF NOT EXISTS "GiangVienQuotas" (
                "MaGiangVien" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "StorageUsedMb" bigint NOT NULL DEFAULT 0,
                "StorageLimitMb" bigint NOT NULL DEFAULT 51200,
                "AiBalanceUsd" numeric(10,4) NOT NULL DEFAULT 0,
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now()
            );

            CREATE TABLE IF NOT EXISTS "AIBalanceHolds" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "MaGiangVien" integer NOT NULL,
                "MaBaiHoc" integer NOT NULL,
                "AmountUsd" numeric(10,4) NOT NULL,
                "Status" character varying(20) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
                "SettledAt" timestamp with time zone NULL
            );

            CREATE TABLE IF NOT EXISTS "WebhookLogs" (
                "NotificationId" character varying(128) PRIMARY KEY,
                "NotificationType" character varying(50) NOT NULL,
                "Payload" jsonb NOT NULL,
                "ProcessedAt" timestamp with time zone NOT NULL DEFAULT now()
            );

            ALTER TABLE "LichSuPhongVans" ADD COLUMN IF NOT EXISTS "CapNhatGhiChuLuc" timestamp with time zone NULL;
            ALTER TABLE "LichSuPhongVans" ADD COLUMN IF NOT EXISTS "GhiChu" character varying(5000) NOT NULL DEFAULT '';

            -- I.2: unique index (partial) chống TOCTOU race tạo 2 hồ sơ giảng viên trùng
            -- email/tài khoản/số giấy tờ khi đang chờ xử lý. Chỉ ràng buộc hồ sơ chưa bị từ chối
            -- (TuChoi) để cho phép nộp lại sau khi bị từ chối. Là hàng phòng thủ cuối sau check AnyAsync.
            CREATE UNIQUE INDEX IF NOT EXISTS "UX_HoSoGV_Email_DangXuLy"
                ON "HoSoDangKyGiangViens" (lower("Email")) WHERE "TrangThaiHoSo" <> 'TuChoi';
            CREATE UNIQUE INDEX IF NOT EXISTS "UX_HoSoGV_TaiKhoan_DangXuLy"
                ON "HoSoDangKyGiangViens" (lower("TaiKhoan")) WHERE "TrangThaiHoSo" <> 'TuChoi';
            CREATE UNIQUE INDEX IF NOT EXISTS "UX_HoSoGV_SoGiayTo_DangXuLy"
                ON "HoSoDangKyGiangViens" ("SoGiayTo") WHERE "TrangThaiHoSo" <> 'TuChoi';

            """,
            cancellationToken);
    }
}
