
  create table "public"."ApiKeyAuditLogs" (
    "Id" integer generated by default as identity not null,
    "Action" character varying(50) not null,
    "AdminId" integer not null,
    "KeyApiId" integer not null,
    "BeforeJson" text,
    "AfterJson" text,
    "MetadataJson" text,
    "IpAddress" character varying(50),
    "CreatedAt" timestamp with time zone not null
      );



  create table "public"."BaiHocs" (
    "MaBaiHoc" integer generated by default as identity not null,
    "MaChuong" integer not null,
    "TieuDe" character varying(200) not null,
    "LoaiBaiHoc" character varying(50) not null,
    "NoiDung" text,
    "ThoiLuong" integer,
    "LinkVideo" character varying(500),
    "ThuTu" integer not null,
    "CoQuiz" boolean not null
      );



  create table "public"."BaiTapThucHanhs" (
    "MaBaiTapTH" integer generated by default as identity not null,
    "MaBaiTap" integer not null,
    "TieuDe" character varying(255) not null,
    "MoTaDeBai" text not null,
    "NgonNgu" character varying(50) not null,
    "MucDo" character varying(50) not null,
    "LoiGiaiMau" text,
    "GoiY" text,
    "NgayTao" timestamp with time zone not null,
    "TrangThai" boolean not null
      );



  create table "public"."BaiTap_Quizs" (
    "MaBaiTapQuiz" integer generated by default as identity not null,
    "MaBaiTap" integer not null,
    "ThoiGianLamBai" integer,
    "DiemCanDat" double precision not null,
    "ChoPhepLamLai" boolean not null,
    "DaoCauHoi" boolean not null,
    "DuLieuCauHoi" text not null
      );



  create table "public"."BaiTaps" (
    "MaBaiTap" integer generated by default as identity not null,
    "MaBaiHoc" integer not null
      );



  create table "public"."BinhLuans" (
    "MaBinhLuan" integer generated by default as identity not null,
    "MaNguoiDung" integer not null,
    "MaBaiHoc" integer not null,
    "NoiDung" text not null,
    "MaBinhLuanCha" integer,
    "NgayTao" timestamp with time zone not null
      );



  create table "public"."CauHinhs" (
    "MaKhoa" character varying(100) not null,
    "GiaTri" text,
    "MoTa" character varying(255),
    "NgayCapNhat" timestamp with time zone
      );



  create table "public"."ChiTietDonHangs" (
    "MaChiTiet" integer generated by default as identity not null,
    "MaDonHang" integer not null,
    "MaKhoaHoc" integer not null,
    "DonGia" numeric(18,2) not null,
    "GiamGia" numeric(18,2) not null,
    "ThanhTien" numeric(18,2) not null
      );



  create table "public"."ChungChiKhoaHocs" (
    "MaChungChiKhoaHoc" integer generated by default as identity not null,
    "MaChungChi" character varying(50) not null,
    "MaKhoaHoc" integer not null,
    "MaNguoiDung" integer not null,
    "MaKetQuaKiemTraChungChi" integer,
    "HoTenHienThi" character varying(200),
    "EmailNhan" character varying(200),
    "DaGuiEmail" boolean not null,
    "NgayGuiEmail" timestamp with time zone,
    "NgayCap" timestamp with time zone not null
      );



  create table "public"."ChuongHocs" (
    "MaChuong" integer generated by default as identity not null,
    "MaKhoaHoc" integer not null,
    "TenChuong" character varying(200) not null,
    "ThuTu" integer not null
      );



  create table "public"."DangKyKhoaHocs" (
    "MaDangKy" integer generated by default as identity not null,
    "MaNguoiDung" integer not null,
    "MaKhoaHoc" integer not null,
    "NgayDangKy" timestamp with time zone not null,
    "TrangThai" character varying(50),
    "TienDo" integer not null
      );



  create table "public"."DanhGias" (
    "MaDanhGia" integer generated by default as identity not null,
    "MaNguoiDung" integer not null,
    "MaKhoaHoc" integer not null,
    "SoSao" integer not null,
    "NhanXet" character varying(1000),
    "NgayDanhGia" timestamp with time zone not null,
    "TrangThai" character varying(20) not null
      );



  create table "public"."DoanhThuGiangViens" (
    "MaDoanhThu" integer generated by default as identity not null,
    "MaGiangVien" integer not null,
    "MaDonHang" integer not null,
    "TongTienDonHang" numeric(18,2) not null,
    "PhiNenTang" numeric(18,2) not null,
    "ThucNhanGiangVien" numeric(18,2) not null,
    "TrangThaiDoiSoat" character varying(30) not null,
    "CreatedAt" timestamp with time zone not null
      );



  create table "public"."DonHangKhoaHocs" (
    "MaDonHang" integer generated by default as identity not null,
    "MaNguoiDung" integer not null,
    "TongTien" numeric(18,2) not null,
    "TongTienGoc" numeric(18,2) not null,
    "SoTienGiam" numeric(18,2) not null,
    "LoaiTien" character varying(10) not null,
    "TrangThaiDonHang" character varying(30) not null,
    "LoaiDonHang" character varying(30) not null,
    "IdempotencyKey" character varying(100) not null,
    "MaVoucher" integer,
    "CodeVoucher" character varying(40),
    "CreatedAt" timestamp with time zone not null,
    "UpdatedAt" timestamp with time zone not null,
    "ExpiredAt" timestamp with time zone
      );



  create table "public"."GhiChuAIs" (
    "Id" integer generated by default as identity not null,
    "MaNguoiDung" integer not null,
    "MaBaiHoc" integer not null,
    "NoiDung" text not null,
    "NgayTao" timestamp with time zone not null,
    "NgayCapNhat" timestamp with time zone not null
      );



  create table "public"."GhiChuBaiHocs" (
    "Id" integer generated by default as identity not null,
    "MaNguoiDung" integer not null,
    "MaBaiHoc" integer not null,
    "ThoiGianVideo" integer not null,
    "NoiDung" character varying(2000) not null,
    "NgayTao" timestamp with time zone not null
      );



  create table "public"."GiaoDichThanhToans" (
    "MaGiaoDich" integer generated by default as identity not null,
    "MaDonHang" integer not null,
    "CongThanhToan" character varying(30) not null,
    "MaThamChieuNgoai" character varying(100) not null,
    "SoTien" numeric(18,2) not null,
    "TrangThai" character varying(30) not null,
    "RawWebhook" jsonb,
    "PaidAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone not null,
    "UpdatedAt" timestamp with time zone not null
      );



  create table "public"."HoTroRutTienGiangViens" (
    "MaHoTroRutTienGiangVien" integer generated by default as identity not null,
    "MaYeuCauRutTien" integer not null,
    "MaGiangVien" integer not null,
    "TrangThaiHoTro" character varying(30) not null,
    "ThongTinLienLac" character varying(200) not null,
    "NoiDungGiangVien" character varying(500),
    "GhiChuAdmin" character varying(500),
    "MaQuanTriVienXuLy" integer,
    "CreatedAt" timestamp with time zone not null,
    "UpdatedAt" timestamp with time zone not null,
    "XuLyLuc" timestamp with time zone
      );



  create table "public"."KetQuaKiemTraChungChis" (
    "MaKetQuaKiemTraChungChi" integer generated by default as identity not null,
    "MaKhoaHoc" integer not null,
    "MaNguoiDung" integer not null,
    "DiemSo" double precision not null,
    "SoCauDung" integer not null,
    "TongSoCau" integer not null,
    "DaDat" boolean not null,
    "ChiTietLamBaiJSON" text not null,
    "NgayThi" timestamp with time zone not null
      );



  create table "public"."KetQuaLamBais" (
    "MaKetQuaBaiNop" integer generated by default as identity not null,
    "MaNguoiDung" integer not null,
    "MaBaiTap" integer not null,
    "NoiDungNopJSON" text not null,
    "DiemSo" real not null,
    "TrangThai" boolean not null,
    "NgayNop" timestamp with time zone not null
      );



  create table "public"."KeyAPIs" (
    "ID" integer generated by default as identity not null,
    "TenKey" character varying(100) not null,
    "MaKeyMaHoa" text not null,
    "LoaiKey" character varying(20) not null,
    "TrangThai" boolean not null,
    "ThuTuUuTien" integer not null,
    "HanMucRequest" integer not null,
    "HanMucToken" integer not null,
    "NgayTao" timestamp with time zone not null,
    "DeletedAt" timestamp with time zone,
    "DeletedBy" integer,
    "LastUsageResetAt" timestamp with time zone
      );



  create table "public"."KhoaHocs" (
    "MaKhoaHoc" integer generated by default as identity not null,
    "MaGiangVien" integer not null,
    "TenKhoaHoc" character varying(200) not null,
    "MoTa" text,
    "HinhAnh" character varying(500),
    "TrangThai" character varying(50),
    "DiemDanhGiaTB" double precision not null,
    "LinhVuc" character varying(100) not null,
    "TrinhDo" character varying(50) not null,
    "ThoiLuongGio" integer not null,
    "KyNangChinh" character varying(500) not null,
    "CoChungChi" boolean not null,
    "TenChungChi" character varying(200),
    "DiemDatChungChi" double precision not null,
    "SoCauHoiChungChi" integer not null,
    "ThoiGianLamBaiChungChi" integer not null,
    "DuLieuDeChungChiJSON" text,
    "NguonDeChungChi" character varying(50),
    "NgayTaoDeChungChi" timestamp with time zone,
    "GiaKhoaHoc" numeric(18,2) not null,
    "DonViTienTe" character varying(10) not null,
    "ChoPhepMua" boolean not null,
    "NgayTao" timestamp with time zone not null
      );



  create table "public"."LoTrinhAIs" (
    "MaLoTrinh" integer generated by default as identity not null,
    "MaNguoiDung" integer not null,
    "YeuCau" text not null,
    "NoiDungJSON" text not null,
    "TrangThai" character varying(50),
    "NgayTao" timestamp with time zone not null
      );



  create table "public"."MaGiamGiaKhoaHocs" (
    "MaLienKet" integer generated by default as identity not null,
    "MaVoucher" integer not null,
    "MaKhoaHoc" integer not null
      );



  create table "public"."MaGiamGias" (
    "MaVoucher" integer generated by default as identity not null,
    "Code" character varying(40) not null,
    "TenChuongTrinh" character varying(100) not null,
    "LoaiGiamGia" character varying(20) not null,
    "GiaTriGiam" numeric(18,2) not null,
    "GiamToiDa" numeric(18,2),
    "DonHangToiThieu" numeric(18,2) not null,
    "MaNguoiTao" integer not null,
    "LoaiNguoiTao" character varying(20) not null,
    "PhamViApDung" character varying(30) not null,
    "ChoPhepApDungChoQuaTang" boolean not null,
    "SoLuongToiDa" integer not null,
    "SoLuongDaDung" integer not null,
    "KichHoat" boolean not null,
    "BatDauAt" timestamp with time zone not null,
    "KetThucAt" timestamp with time zone not null
      );



  create table "public"."MaQuaTangHocViens" (
    "MaQuaTang" integer generated by default as identity not null,
    "Code" character varying(40) not null,
    "MaDonHang" integer not null,
    "MaKhoaHoc" integer not null,
    "MaNguoiTang" integer not null,
    "MaNguoiNhan" integer,
    "TrangThai" character varying(30) not null,
    "CreatedAt" timestamp with time zone not null,
    "ActivatedAt" timestamp with time zone,
    "RedeemedAt" timestamp with time zone,
    "ExpiredAt" timestamp with time zone
      );



  create table "public"."NguoiDungs" (
    "MaNguoiDung" integer generated by default as identity not null,
    "TaiKhoan" character varying(50) not null,
    "MatKhau" character varying(255) not null,
    "GoogleID" character varying(100),
    "HoTen" character varying(100),
    "Email" character varying(100),
    "AnhDaiDien" character varying(500),
    "VaiTro" integer not null,
    "TrangThai" character varying(20),
    "NgayThamGia" timestamp with time zone not null,
    "LyDoKhoa" text,
    "ThoiGianMoKhoa" timestamp with time zone,
    "NgayDangNhapCuoi" timestamp with time zone,
    "MaOTP" character varying(10),
    "ThoiGianHetHanOTP" timestamp with time zone,
    "MaNganHangNhanTien" character varying(50),
    "SoTaiKhoanNhanTien" character varying(50),
    "TenTaiKhoanNhanTien" character varying(255)
      );



  create table "public"."NhatKySuDungs" (
    "ID" bigint generated by default as identity not null,
    "ID_Key" integer not null,
    "SoTokenTieuHao" integer not null,
    "ThoiGianGoi" timestamp with time zone not null,
    "MaTrangThai" integer not null,
    "DuongDanAPI" character varying(255) not null
      );



  create table "public"."PhienDangNhap" (
    "MaPhien" integer generated by default as identity not null,
    "MaNguoiDung" integer not null,
    "MaThietBi" character varying(255) not null,
    "TenThietBi" character varying(255) not null,
    "DiaChiIP" character varying(50),
    "ThoiGianDangNhap" timestamp with time zone not null,
    "ThoiGianHoatDongCuoi" timestamp with time zone not null,
    "DangHoatDong" boolean not null
      );



  create table "public"."QuaTangKhoaHocs" (
    "MaQuaTang" integer generated by default as identity not null,
    "MaKhoaHoc" integer not null,
    "MaNguoiNhan" integer not null,
    "MaNguoiTang" integer not null,
    "LoaiNguoiTang" character varying(30) not null,
    "TrangThai" character varying(30) not null,
    "LoiNhan" character varying(500),
    "CreatedAt" timestamp with time zone not null,
    "CompletedAt" timestamp with time zone
      );



  create table "public"."TestCaseThucHanhs" (
    "MaTestCase" integer generated by default as identity not null,
    "MaBaiTapThucHanh" integer not null,
    "InputDuLieu" text not null,
    "OutputMongDoi" text not null,
    "MoTa" text,
    "LaTestAn" boolean not null,
    "ThuTu" integer not null,
    "Diem" integer not null,
    "NgayTao" timestamp with time zone not null
      );



  create table "public"."ThongBaoEmailThanhToans" (
    "MaThongBao" integer generated by default as identity not null,
    "MaDonHang" integer not null,
    "LoaiThongBao" character varying(50) not null,
    "EmailNhan" character varying(255) not null,
    "TrangThai" character varying(20) not null,
    "SoLanThu" integer not null,
    "LoiCuoi" character varying(1000),
    "SentAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone not null,
    "UpdatedAt" timestamp with time zone not null
      );



  create table "public"."TienDoBaiHocs" (
    "MaTienDo" integer generated by default as identity not null,
    "MaNguoiDung" integer not null,
    "MaBaiHoc" integer not null,
    "DaXem" boolean not null,
    "ThoiGianHoc" integer not null,
    "NgayCapNhat" timestamp with time zone not null
      );



  create table "public"."VideoChapters" (
    "MaChapter" integer generated by default as identity not null,
    "MaBaiHoc" integer not null,
    "ThoiGianBatDau" integer not null,
    "ThoiGianKetThuc" integer not null,
    "KienThucChinh" character varying(500) not null,
    "BatBuoc" boolean not null
      );



  create table "public"."VideoQuizs" (
    "MaVideoQuiz" integer generated by default as identity not null,
    "MaChapter" integer not null,
    "CauHoi" character varying(1000) not null,
    "DapAnA" character varying(500) not null,
    "DapAnB" character varying(500) not null,
    "DapAnC" character varying(500),
    "DapAnD" character varying(500),
    "DapAnDung" character varying(5) not null
      );



  create table "public"."YeuCauRutTienGiangViens" (
    "MaYeuCauRutTien" integer generated by default as identity not null,
    "MaGiangVien" integer not null,
    "SoTienYeuCau" numeric(18,2) not null,
    "TrangThaiYeuCau" character varying(30) not null,
    "LoaiTien" character varying(30) not null,
    "MaNganHangNhan" character varying(50) not null,
    "SoTaiKhoanNhan" character varying(50) not null,
    "TenTaiKhoanNhan" character varying(255) not null,
    "NoiDungChuyenKhoan" character varying(120),
    "DuongDanAnhQr" character varying(500),
    "SoTienDaChuyen" numeric(18,2),
    "MaGiaoDichSePay" bigint,
    "CreatedAt" timestamp with time zone not null,
    "DuyetLuc" timestamp with time zone,
    "MaQuanTriVienDuyet" integer,
    "ChuyenKhoanThanhCongLuc" timestamp with time zone,
    "GuiEmailRutTienThanhCongLuc" timestamp with time zone,
    "GhiChuAdmin" character varying(500)
      );



  create table "public"."__EFMigrationsHistory" (
    "MigrationId" character varying(150) not null,
    "ProductVersion" character varying(32) not null
      );


CREATE INDEX "IX_BaiHocs_MaChuong" ON public."BaiHocs" USING btree ("MaChuong");

CREATE UNIQUE INDEX "IX_BaiTapThucHanhs_MaBaiTap" ON public."BaiTapThucHanhs" USING btree ("MaBaiTap");

CREATE UNIQUE INDEX "IX_BaiTap_Quizs_MaBaiTap" ON public."BaiTap_Quizs" USING btree ("MaBaiTap");

CREATE INDEX "IX_BaiTaps_MaBaiHoc" ON public."BaiTaps" USING btree ("MaBaiHoc");

CREATE INDEX "IX_BinhLuans_MaBaiHoc" ON public."BinhLuans" USING btree ("MaBaiHoc");

CREATE INDEX "IX_BinhLuans_MaBinhLuanCha" ON public."BinhLuans" USING btree ("MaBinhLuanCha");

CREATE INDEX "IX_BinhLuans_MaNguoiDung" ON public."BinhLuans" USING btree ("MaNguoiDung");

CREATE INDEX "IX_ChiTietDonHangs_MaDonHang" ON public."ChiTietDonHangs" USING btree ("MaDonHang");

CREATE INDEX "IX_ChiTietDonHangs_MaKhoaHoc" ON public."ChiTietDonHangs" USING btree ("MaKhoaHoc");

CREATE UNIQUE INDEX "IX_ChungChiKhoaHocs_MaChungChi" ON public."ChungChiKhoaHocs" USING btree ("MaChungChi");

CREATE INDEX "IX_ChungChiKhoaHocs_MaKetQuaKiemTraChungChi" ON public."ChungChiKhoaHocs" USING btree ("MaKetQuaKiemTraChungChi");

CREATE INDEX "IX_ChungChiKhoaHocs_MaKhoaHoc" ON public."ChungChiKhoaHocs" USING btree ("MaKhoaHoc");

CREATE UNIQUE INDEX "IX_ChungChiKhoaHocs_MaNguoiDung_MaKhoaHoc" ON public."ChungChiKhoaHocs" USING btree ("MaNguoiDung", "MaKhoaHoc");

CREATE INDEX "IX_ChuongHocs_MaKhoaHoc" ON public."ChuongHocs" USING btree ("MaKhoaHoc");

CREATE INDEX "IX_DangKyKhoaHocs_MaKhoaHoc" ON public."DangKyKhoaHocs" USING btree ("MaKhoaHoc");

CREATE INDEX "IX_DangKyKhoaHocs_MaNguoiDung" ON public."DangKyKhoaHocs" USING btree ("MaNguoiDung");

CREATE INDEX "IX_DanhGias_MaKhoaHoc" ON public."DanhGias" USING btree ("MaKhoaHoc");

CREATE UNIQUE INDEX "IX_DanhGias_MaNguoiDung_MaKhoaHoc" ON public."DanhGias" USING btree ("MaNguoiDung", "MaKhoaHoc");

CREATE INDEX "IX_DoanhThuGiangViens_MaDonHang" ON public."DoanhThuGiangViens" USING btree ("MaDonHang");

CREATE INDEX "IX_DoanhThuGiangViens_MaGiangVien" ON public."DoanhThuGiangViens" USING btree ("MaGiangVien");

CREATE UNIQUE INDEX "IX_DonHangKhoaHocs_IdempotencyKey" ON public."DonHangKhoaHocs" USING btree ("IdempotencyKey");

CREATE INDEX "IX_DonHangKhoaHocs_MaNguoiDung" ON public."DonHangKhoaHocs" USING btree ("MaNguoiDung");

CREATE INDEX "IX_DonHangKhoaHocs_MaVoucher" ON public."DonHangKhoaHocs" USING btree ("MaVoucher");

CREATE INDEX "IX_GhiChuAIs_MaBaiHoc" ON public."GhiChuAIs" USING btree ("MaBaiHoc");

CREATE INDEX "IX_GhiChuAIs_MaNguoiDung" ON public."GhiChuAIs" USING btree ("MaNguoiDung");

CREATE INDEX "IX_GhiChuBaiHocs_MaBaiHoc" ON public."GhiChuBaiHocs" USING btree ("MaBaiHoc");

CREATE INDEX "IX_GhiChuBaiHocs_MaNguoiDung" ON public."GhiChuBaiHocs" USING btree ("MaNguoiDung");

CREATE INDEX "IX_GiaoDichThanhToans_MaDonHang" ON public."GiaoDichThanhToans" USING btree ("MaDonHang");

CREATE UNIQUE INDEX "IX_GiaoDichThanhToans_MaThamChieuNgoai" ON public."GiaoDichThanhToans" USING btree ("MaThamChieuNgoai");

CREATE INDEX "IX_HoTroRutTienGiangViens_MaGiangVien" ON public."HoTroRutTienGiangViens" USING btree ("MaGiangVien");

CREATE INDEX "IX_HoTroRutTienGiangViens_MaQuanTriVienXuLy" ON public."HoTroRutTienGiangViens" USING btree ("MaQuanTriVienXuLy");

CREATE INDEX "IX_HoTroRutTienGiangViens_MaYeuCauRutTien_TrangThaiHoTro" ON public."HoTroRutTienGiangViens" USING btree ("MaYeuCauRutTien", "TrangThaiHoTro");

CREATE INDEX "IX_KetQuaKiemTraChungChis_MaKhoaHoc" ON public."KetQuaKiemTraChungChis" USING btree ("MaKhoaHoc");

CREATE INDEX "IX_KetQuaKiemTraChungChis_MaNguoiDung" ON public."KetQuaKiemTraChungChis" USING btree ("MaNguoiDung");

CREATE INDEX "IX_KetQuaLamBais_MaBaiTap" ON public."KetQuaLamBais" USING btree ("MaBaiTap");

CREATE INDEX "IX_KetQuaLamBais_MaNguoiDung" ON public."KetQuaLamBais" USING btree ("MaNguoiDung");

CREATE INDEX "IX_KhoaHocs_MaGiangVien" ON public."KhoaHocs" USING btree ("MaGiangVien");

CREATE INDEX "IX_LoTrinhAIs_MaNguoiDung" ON public."LoTrinhAIs" USING btree ("MaNguoiDung");

CREATE INDEX "IX_MaGiamGiaKhoaHocs_MaKhoaHoc" ON public."MaGiamGiaKhoaHocs" USING btree ("MaKhoaHoc");

CREATE UNIQUE INDEX "IX_MaGiamGiaKhoaHocs_MaVoucher_MaKhoaHoc" ON public."MaGiamGiaKhoaHocs" USING btree ("MaVoucher", "MaKhoaHoc");

CREATE UNIQUE INDEX "IX_MaGiamGias_Code" ON public."MaGiamGias" USING btree ("Code");

CREATE INDEX "IX_MaGiamGias_MaNguoiTao" ON public."MaGiamGias" USING btree ("MaNguoiTao");

CREATE UNIQUE INDEX "IX_MaQuaTangHocViens_Code" ON public."MaQuaTangHocViens" USING btree ("Code");

CREATE INDEX "IX_MaQuaTangHocViens_MaDonHang" ON public."MaQuaTangHocViens" USING btree ("MaDonHang");

CREATE INDEX "IX_MaQuaTangHocViens_MaKhoaHoc" ON public."MaQuaTangHocViens" USING btree ("MaKhoaHoc");

CREATE INDEX "IX_MaQuaTangHocViens_MaNguoiNhan" ON public."MaQuaTangHocViens" USING btree ("MaNguoiNhan");

CREATE INDEX "IX_MaQuaTangHocViens_MaNguoiTang_TrangThai_CreatedAt" ON public."MaQuaTangHocViens" USING btree ("MaNguoiTang", "TrangThai", "CreatedAt");

CREATE UNIQUE INDEX "IX_NguoiDungs_Email" ON public."NguoiDungs" USING btree ("Email");

CREATE UNIQUE INDEX "IX_NguoiDungs_TaiKhoan" ON public."NguoiDungs" USING btree ("TaiKhoan");

CREATE INDEX "IX_NhatKySuDungs_ID_Key" ON public."NhatKySuDungs" USING btree ("ID_Key");

CREATE INDEX "IX_PhienDangNhap_MaNguoiDung" ON public."PhienDangNhap" USING btree ("MaNguoiDung");

CREATE INDEX "IX_QuaTangKhoaHocs_MaKhoaHoc_MaNguoiNhan_TrangThai" ON public."QuaTangKhoaHocs" USING btree ("MaKhoaHoc", "MaNguoiNhan", "TrangThai");

CREATE INDEX "IX_QuaTangKhoaHocs_MaNguoiNhan" ON public."QuaTangKhoaHocs" USING btree ("MaNguoiNhan");

CREATE INDEX "IX_QuaTangKhoaHocs_MaNguoiTang_MaKhoaHoc_CreatedAt" ON public."QuaTangKhoaHocs" USING btree ("MaNguoiTang", "MaKhoaHoc", "CreatedAt");

CREATE INDEX "IX_TestCaseThucHanhs_MaBaiTapThucHanh" ON public."TestCaseThucHanhs" USING btree ("MaBaiTapThucHanh");

CREATE UNIQUE INDEX "IX_ThongBaoEmailThanhToans_MaDonHang_LoaiThongBao_EmailNhan" ON public."ThongBaoEmailThanhToans" USING btree ("MaDonHang", "LoaiThongBao", "EmailNhan");

CREATE INDEX "IX_TienDoBaiHocs_MaBaiHoc" ON public."TienDoBaiHocs" USING btree ("MaBaiHoc");

CREATE UNIQUE INDEX "IX_TienDoBaiHocs_MaNguoiDung_MaBaiHoc" ON public."TienDoBaiHocs" USING btree ("MaNguoiDung", "MaBaiHoc");

CREATE INDEX "IX_VideoChapters_MaBaiHoc" ON public."VideoChapters" USING btree ("MaBaiHoc");

CREATE INDEX "IX_VideoQuizs_MaChapter" ON public."VideoQuizs" USING btree ("MaChapter");

CREATE INDEX "IX_YeuCauRutTienGiangViens_MaGiangVien" ON public."YeuCauRutTienGiangViens" USING btree ("MaGiangVien");

CREATE UNIQUE INDEX "IX_YeuCauRutTienGiangViens_MaGiaoDichSePay" ON public."YeuCauRutTienGiangViens" USING btree ("MaGiaoDichSePay");

CREATE INDEX "IX_YeuCauRutTienGiangViens_MaQuanTriVienDuyet" ON public."YeuCauRutTienGiangViens" USING btree ("MaQuanTriVienDuyet");

CREATE UNIQUE INDEX "IX_YeuCauRutTienGiangViens_NoiDungChuyenKhoan" ON public."YeuCauRutTienGiangViens" USING btree ("NoiDungChuyenKhoan");

CREATE UNIQUE INDEX "PK_ApiKeyAuditLogs" ON public."ApiKeyAuditLogs" USING btree ("Id");

CREATE UNIQUE INDEX "PK_BaiHocs" ON public."BaiHocs" USING btree ("MaBaiHoc");

CREATE UNIQUE INDEX "PK_BaiTapThucHanhs" ON public."BaiTapThucHanhs" USING btree ("MaBaiTapTH");

CREATE UNIQUE INDEX "PK_BaiTap_Quizs" ON public."BaiTap_Quizs" USING btree ("MaBaiTapQuiz");

CREATE UNIQUE INDEX "PK_BaiTaps" ON public."BaiTaps" USING btree ("MaBaiTap");

CREATE UNIQUE INDEX "PK_BinhLuans" ON public."BinhLuans" USING btree ("MaBinhLuan");

CREATE UNIQUE INDEX "PK_CauHinhs" ON public."CauHinhs" USING btree ("MaKhoa");

CREATE UNIQUE INDEX "PK_ChiTietDonHangs" ON public."ChiTietDonHangs" USING btree ("MaChiTiet");

CREATE UNIQUE INDEX "PK_ChungChiKhoaHocs" ON public."ChungChiKhoaHocs" USING btree ("MaChungChiKhoaHoc");

CREATE UNIQUE INDEX "PK_ChuongHocs" ON public."ChuongHocs" USING btree ("MaChuong");

CREATE UNIQUE INDEX "PK_DangKyKhoaHocs" ON public."DangKyKhoaHocs" USING btree ("MaDangKy");

CREATE UNIQUE INDEX "PK_DanhGias" ON public."DanhGias" USING btree ("MaDanhGia");

CREATE UNIQUE INDEX "PK_DoanhThuGiangViens" ON public."DoanhThuGiangViens" USING btree ("MaDoanhThu");

CREATE UNIQUE INDEX "PK_DonHangKhoaHocs" ON public."DonHangKhoaHocs" USING btree ("MaDonHang");

CREATE UNIQUE INDEX "PK_GhiChuAIs" ON public."GhiChuAIs" USING btree ("Id");

CREATE UNIQUE INDEX "PK_GhiChuBaiHocs" ON public."GhiChuBaiHocs" USING btree ("Id");

CREATE UNIQUE INDEX "PK_GiaoDichThanhToans" ON public."GiaoDichThanhToans" USING btree ("MaGiaoDich");

CREATE UNIQUE INDEX "PK_HoTroRutTienGiangViens" ON public."HoTroRutTienGiangViens" USING btree ("MaHoTroRutTienGiangVien");

CREATE UNIQUE INDEX "PK_KetQuaKiemTraChungChis" ON public."KetQuaKiemTraChungChis" USING btree ("MaKetQuaKiemTraChungChi");

CREATE UNIQUE INDEX "PK_KetQuaLamBais" ON public."KetQuaLamBais" USING btree ("MaKetQuaBaiNop");

CREATE UNIQUE INDEX "PK_KeyAPIs" ON public."KeyAPIs" USING btree ("ID");

CREATE UNIQUE INDEX "PK_KhoaHocs" ON public."KhoaHocs" USING btree ("MaKhoaHoc");

CREATE UNIQUE INDEX "PK_LoTrinhAIs" ON public."LoTrinhAIs" USING btree ("MaLoTrinh");

CREATE UNIQUE INDEX "PK_MaGiamGiaKhoaHocs" ON public."MaGiamGiaKhoaHocs" USING btree ("MaLienKet");

CREATE UNIQUE INDEX "PK_MaGiamGias" ON public."MaGiamGias" USING btree ("MaVoucher");

CREATE UNIQUE INDEX "PK_MaQuaTangHocViens" ON public."MaQuaTangHocViens" USING btree ("MaQuaTang");

CREATE UNIQUE INDEX "PK_NguoiDungs" ON public."NguoiDungs" USING btree ("MaNguoiDung");

CREATE UNIQUE INDEX "PK_NhatKySuDungs" ON public."NhatKySuDungs" USING btree ("ID");

CREATE UNIQUE INDEX "PK_PhienDangNhap" ON public."PhienDangNhap" USING btree ("MaPhien");

CREATE UNIQUE INDEX "PK_QuaTangKhoaHocs" ON public."QuaTangKhoaHocs" USING btree ("MaQuaTang");

CREATE UNIQUE INDEX "PK_TestCaseThucHanhs" ON public."TestCaseThucHanhs" USING btree ("MaTestCase");

CREATE UNIQUE INDEX "PK_ThongBaoEmailThanhToans" ON public."ThongBaoEmailThanhToans" USING btree ("MaThongBao");

CREATE UNIQUE INDEX "PK_TienDoBaiHocs" ON public."TienDoBaiHocs" USING btree ("MaTienDo");

CREATE UNIQUE INDEX "PK_VideoChapters" ON public."VideoChapters" USING btree ("MaChapter");

CREATE UNIQUE INDEX "PK_VideoQuizs" ON public."VideoQuizs" USING btree ("MaVideoQuiz");

CREATE UNIQUE INDEX "PK_YeuCauRutTienGiangViens" ON public."YeuCauRutTienGiangViens" USING btree ("MaYeuCauRutTien");

CREATE UNIQUE INDEX "PK___EFMigrationsHistory" ON public."__EFMigrationsHistory" USING btree ("MigrationId");

alter table "public"."ApiKeyAuditLogs" add constraint "PK_ApiKeyAuditLogs" PRIMARY KEY using index "PK_ApiKeyAuditLogs";

alter table "public"."BaiHocs" add constraint "PK_BaiHocs" PRIMARY KEY using index "PK_BaiHocs";

alter table "public"."BaiTapThucHanhs" add constraint "PK_BaiTapThucHanhs" PRIMARY KEY using index "PK_BaiTapThucHanhs";

alter table "public"."BaiTap_Quizs" add constraint "PK_BaiTap_Quizs" PRIMARY KEY using index "PK_BaiTap_Quizs";

alter table "public"."BaiTaps" add constraint "PK_BaiTaps" PRIMARY KEY using index "PK_BaiTaps";

alter table "public"."BinhLuans" add constraint "PK_BinhLuans" PRIMARY KEY using index "PK_BinhLuans";

alter table "public"."CauHinhs" add constraint "PK_CauHinhs" PRIMARY KEY using index "PK_CauHinhs";

alter table "public"."ChiTietDonHangs" add constraint "PK_ChiTietDonHangs" PRIMARY KEY using index "PK_ChiTietDonHangs";

alter table "public"."ChungChiKhoaHocs" add constraint "PK_ChungChiKhoaHocs" PRIMARY KEY using index "PK_ChungChiKhoaHocs";

alter table "public"."ChuongHocs" add constraint "PK_ChuongHocs" PRIMARY KEY using index "PK_ChuongHocs";

alter table "public"."DangKyKhoaHocs" add constraint "PK_DangKyKhoaHocs" PRIMARY KEY using index "PK_DangKyKhoaHocs";

alter table "public"."DanhGias" add constraint "PK_DanhGias" PRIMARY KEY using index "PK_DanhGias";

alter table "public"."DoanhThuGiangViens" add constraint "PK_DoanhThuGiangViens" PRIMARY KEY using index "PK_DoanhThuGiangViens";

alter table "public"."DonHangKhoaHocs" add constraint "PK_DonHangKhoaHocs" PRIMARY KEY using index "PK_DonHangKhoaHocs";

alter table "public"."GhiChuAIs" add constraint "PK_GhiChuAIs" PRIMARY KEY using index "PK_GhiChuAIs";

alter table "public"."GhiChuBaiHocs" add constraint "PK_GhiChuBaiHocs" PRIMARY KEY using index "PK_GhiChuBaiHocs";

alter table "public"."GiaoDichThanhToans" add constraint "PK_GiaoDichThanhToans" PRIMARY KEY using index "PK_GiaoDichThanhToans";

alter table "public"."HoTroRutTienGiangViens" add constraint "PK_HoTroRutTienGiangViens" PRIMARY KEY using index "PK_HoTroRutTienGiangViens";

alter table "public"."KetQuaKiemTraChungChis" add constraint "PK_KetQuaKiemTraChungChis" PRIMARY KEY using index "PK_KetQuaKiemTraChungChis";

alter table "public"."KetQuaLamBais" add constraint "PK_KetQuaLamBais" PRIMARY KEY using index "PK_KetQuaLamBais";

alter table "public"."KeyAPIs" add constraint "PK_KeyAPIs" PRIMARY KEY using index "PK_KeyAPIs";

alter table "public"."KhoaHocs" add constraint "PK_KhoaHocs" PRIMARY KEY using index "PK_KhoaHocs";

alter table "public"."LoTrinhAIs" add constraint "PK_LoTrinhAIs" PRIMARY KEY using index "PK_LoTrinhAIs";

alter table "public"."MaGiamGiaKhoaHocs" add constraint "PK_MaGiamGiaKhoaHocs" PRIMARY KEY using index "PK_MaGiamGiaKhoaHocs";

alter table "public"."MaGiamGias" add constraint "PK_MaGiamGias" PRIMARY KEY using index "PK_MaGiamGias";

alter table "public"."MaQuaTangHocViens" add constraint "PK_MaQuaTangHocViens" PRIMARY KEY using index "PK_MaQuaTangHocViens";

alter table "public"."NguoiDungs" add constraint "PK_NguoiDungs" PRIMARY KEY using index "PK_NguoiDungs";

alter table "public"."NhatKySuDungs" add constraint "PK_NhatKySuDungs" PRIMARY KEY using index "PK_NhatKySuDungs";

alter table "public"."PhienDangNhap" add constraint "PK_PhienDangNhap" PRIMARY KEY using index "PK_PhienDangNhap";

alter table "public"."QuaTangKhoaHocs" add constraint "PK_QuaTangKhoaHocs" PRIMARY KEY using index "PK_QuaTangKhoaHocs";

alter table "public"."TestCaseThucHanhs" add constraint "PK_TestCaseThucHanhs" PRIMARY KEY using index "PK_TestCaseThucHanhs";

alter table "public"."ThongBaoEmailThanhToans" add constraint "PK_ThongBaoEmailThanhToans" PRIMARY KEY using index "PK_ThongBaoEmailThanhToans";

alter table "public"."TienDoBaiHocs" add constraint "PK_TienDoBaiHocs" PRIMARY KEY using index "PK_TienDoBaiHocs";

alter table "public"."VideoChapters" add constraint "PK_VideoChapters" PRIMARY KEY using index "PK_VideoChapters";

alter table "public"."VideoQuizs" add constraint "PK_VideoQuizs" PRIMARY KEY using index "PK_VideoQuizs";

alter table "public"."YeuCauRutTienGiangViens" add constraint "PK_YeuCauRutTienGiangViens" PRIMARY KEY using index "PK_YeuCauRutTienGiangViens";

alter table "public"."__EFMigrationsHistory" add constraint "PK___EFMigrationsHistory" PRIMARY KEY using index "PK___EFMigrationsHistory";

alter table "public"."BaiHocs" add constraint "FK_BaiHocs_ChuongHocs_MaChuong" FOREIGN KEY ("MaChuong") REFERENCES public."ChuongHocs"("MaChuong") not valid;

alter table "public"."BaiHocs" validate constraint "FK_BaiHocs_ChuongHocs_MaChuong";

alter table "public"."BaiTapThucHanhs" add constraint "FK_BaiTapThucHanhs_BaiTaps_MaBaiTap" FOREIGN KEY ("MaBaiTap") REFERENCES public."BaiTaps"("MaBaiTap") not valid;

alter table "public"."BaiTapThucHanhs" validate constraint "FK_BaiTapThucHanhs_BaiTaps_MaBaiTap";

alter table "public"."BaiTap_Quizs" add constraint "FK_BaiTap_Quizs_BaiTaps_MaBaiTap" FOREIGN KEY ("MaBaiTap") REFERENCES public."BaiTaps"("MaBaiTap") not valid;

alter table "public"."BaiTap_Quizs" validate constraint "FK_BaiTap_Quizs_BaiTaps_MaBaiTap";

alter table "public"."BaiTaps" add constraint "FK_BaiTaps_BaiHocs_MaBaiHoc" FOREIGN KEY ("MaBaiHoc") REFERENCES public."BaiHocs"("MaBaiHoc") not valid;

alter table "public"."BaiTaps" validate constraint "FK_BaiTaps_BaiHocs_MaBaiHoc";

alter table "public"."BinhLuans" add constraint "FK_BinhLuans_BaiHocs_MaBaiHoc" FOREIGN KEY ("MaBaiHoc") REFERENCES public."BaiHocs"("MaBaiHoc") not valid;

alter table "public"."BinhLuans" validate constraint "FK_BinhLuans_BaiHocs_MaBaiHoc";

alter table "public"."BinhLuans" add constraint "FK_BinhLuans_BinhLuans_MaBinhLuanCha" FOREIGN KEY ("MaBinhLuanCha") REFERENCES public."BinhLuans"("MaBinhLuan") not valid;

alter table "public"."BinhLuans" validate constraint "FK_BinhLuans_BinhLuans_MaBinhLuanCha";

alter table "public"."BinhLuans" add constraint "FK_BinhLuans_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."BinhLuans" validate constraint "FK_BinhLuans_NguoiDungs_MaNguoiDung";

alter table "public"."ChiTietDonHangs" add constraint "FK_ChiTietDonHangs_DonHangKhoaHocs_MaDonHang" FOREIGN KEY ("MaDonHang") REFERENCES public."DonHangKhoaHocs"("MaDonHang") ON DELETE CASCADE not valid;

alter table "public"."ChiTietDonHangs" validate constraint "FK_ChiTietDonHangs_DonHangKhoaHocs_MaDonHang";

alter table "public"."ChiTietDonHangs" add constraint "FK_ChiTietDonHangs_KhoaHocs_MaKhoaHoc" FOREIGN KEY ("MaKhoaHoc") REFERENCES public."KhoaHocs"("MaKhoaHoc") not valid;

alter table "public"."ChiTietDonHangs" validate constraint "FK_ChiTietDonHangs_KhoaHocs_MaKhoaHoc";

alter table "public"."ChungChiKhoaHocs" add constraint "FK_ChungChiKhoaHocs_KetQuaKiemTraChungChis_MaKetQuaKiemTraChun~" FOREIGN KEY ("MaKetQuaKiemTraChungChi") REFERENCES public."KetQuaKiemTraChungChis"("MaKetQuaKiemTraChungChi") not valid;

alter table "public"."ChungChiKhoaHocs" validate constraint "FK_ChungChiKhoaHocs_KetQuaKiemTraChungChis_MaKetQuaKiemTraChun~";

alter table "public"."ChungChiKhoaHocs" add constraint "FK_ChungChiKhoaHocs_KhoaHocs_MaKhoaHoc" FOREIGN KEY ("MaKhoaHoc") REFERENCES public."KhoaHocs"("MaKhoaHoc") not valid;

alter table "public"."ChungChiKhoaHocs" validate constraint "FK_ChungChiKhoaHocs_KhoaHocs_MaKhoaHoc";

alter table "public"."ChungChiKhoaHocs" add constraint "FK_ChungChiKhoaHocs_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."ChungChiKhoaHocs" validate constraint "FK_ChungChiKhoaHocs_NguoiDungs_MaNguoiDung";

alter table "public"."ChuongHocs" add constraint "FK_ChuongHocs_KhoaHocs_MaKhoaHoc" FOREIGN KEY ("MaKhoaHoc") REFERENCES public."KhoaHocs"("MaKhoaHoc") not valid;

alter table "public"."ChuongHocs" validate constraint "FK_ChuongHocs_KhoaHocs_MaKhoaHoc";

alter table "public"."DangKyKhoaHocs" add constraint "FK_DangKyKhoaHocs_KhoaHocs_MaKhoaHoc" FOREIGN KEY ("MaKhoaHoc") REFERENCES public."KhoaHocs"("MaKhoaHoc") not valid;

alter table "public"."DangKyKhoaHocs" validate constraint "FK_DangKyKhoaHocs_KhoaHocs_MaKhoaHoc";

alter table "public"."DangKyKhoaHocs" add constraint "FK_DangKyKhoaHocs_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."DangKyKhoaHocs" validate constraint "FK_DangKyKhoaHocs_NguoiDungs_MaNguoiDung";

alter table "public"."DanhGias" add constraint "FK_DanhGias_KhoaHocs_MaKhoaHoc" FOREIGN KEY ("MaKhoaHoc") REFERENCES public."KhoaHocs"("MaKhoaHoc") not valid;

alter table "public"."DanhGias" validate constraint "FK_DanhGias_KhoaHocs_MaKhoaHoc";

alter table "public"."DanhGias" add constraint "FK_DanhGias_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."DanhGias" validate constraint "FK_DanhGias_NguoiDungs_MaNguoiDung";

alter table "public"."DoanhThuGiangViens" add constraint "FK_DoanhThuGiangViens_DonHangKhoaHocs_MaDonHang" FOREIGN KEY ("MaDonHang") REFERENCES public."DonHangKhoaHocs"("MaDonHang") ON DELETE CASCADE not valid;

alter table "public"."DoanhThuGiangViens" validate constraint "FK_DoanhThuGiangViens_DonHangKhoaHocs_MaDonHang";

alter table "public"."DoanhThuGiangViens" add constraint "FK_DoanhThuGiangViens_NguoiDungs_MaGiangVien" FOREIGN KEY ("MaGiangVien") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."DoanhThuGiangViens" validate constraint "FK_DoanhThuGiangViens_NguoiDungs_MaGiangVien";

alter table "public"."DonHangKhoaHocs" add constraint "FK_DonHangKhoaHocs_MaGiamGias_MaVoucher" FOREIGN KEY ("MaVoucher") REFERENCES public."MaGiamGias"("MaVoucher") ON DELETE SET NULL not valid;

alter table "public"."DonHangKhoaHocs" validate constraint "FK_DonHangKhoaHocs_MaGiamGias_MaVoucher";

alter table "public"."DonHangKhoaHocs" add constraint "FK_DonHangKhoaHocs_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."DonHangKhoaHocs" validate constraint "FK_DonHangKhoaHocs_NguoiDungs_MaNguoiDung";

alter table "public"."GhiChuAIs" add constraint "FK_GhiChuAIs_BaiHocs_MaBaiHoc" FOREIGN KEY ("MaBaiHoc") REFERENCES public."BaiHocs"("MaBaiHoc") ON DELETE CASCADE not valid;

alter table "public"."GhiChuAIs" validate constraint "FK_GhiChuAIs_BaiHocs_MaBaiHoc";

alter table "public"."GhiChuAIs" add constraint "FK_GhiChuAIs_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") ON DELETE CASCADE not valid;

alter table "public"."GhiChuAIs" validate constraint "FK_GhiChuAIs_NguoiDungs_MaNguoiDung";

alter table "public"."GhiChuBaiHocs" add constraint "FK_GhiChuBaiHocs_BaiHocs_MaBaiHoc" FOREIGN KEY ("MaBaiHoc") REFERENCES public."BaiHocs"("MaBaiHoc") not valid;

alter table "public"."GhiChuBaiHocs" validate constraint "FK_GhiChuBaiHocs_BaiHocs_MaBaiHoc";

alter table "public"."GhiChuBaiHocs" add constraint "FK_GhiChuBaiHocs_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."GhiChuBaiHocs" validate constraint "FK_GhiChuBaiHocs_NguoiDungs_MaNguoiDung";

alter table "public"."GiaoDichThanhToans" add constraint "FK_GiaoDichThanhToans_DonHangKhoaHocs_MaDonHang" FOREIGN KEY ("MaDonHang") REFERENCES public."DonHangKhoaHocs"("MaDonHang") ON DELETE CASCADE not valid;

alter table "public"."GiaoDichThanhToans" validate constraint "FK_GiaoDichThanhToans_DonHangKhoaHocs_MaDonHang";

alter table "public"."HoTroRutTienGiangViens" add constraint "FK_HoTroRutTienGiangViens_NguoiDungs_MaGiangVien" FOREIGN KEY ("MaGiangVien") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."HoTroRutTienGiangViens" validate constraint "FK_HoTroRutTienGiangViens_NguoiDungs_MaGiangVien";

alter table "public"."HoTroRutTienGiangViens" add constraint "FK_HoTroRutTienGiangViens_NguoiDungs_MaQuanTriVienXuLy" FOREIGN KEY ("MaQuanTriVienXuLy") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."HoTroRutTienGiangViens" validate constraint "FK_HoTroRutTienGiangViens_NguoiDungs_MaQuanTriVienXuLy";

alter table "public"."HoTroRutTienGiangViens" add constraint "FK_HoTroRutTienGiangViens_YeuCauRutTienGiangViens_MaYeuCauRutT~" FOREIGN KEY ("MaYeuCauRutTien") REFERENCES public."YeuCauRutTienGiangViens"("MaYeuCauRutTien") ON DELETE CASCADE not valid;

alter table "public"."HoTroRutTienGiangViens" validate constraint "FK_HoTroRutTienGiangViens_YeuCauRutTienGiangViens_MaYeuCauRutT~";

alter table "public"."KetQuaKiemTraChungChis" add constraint "FK_KetQuaKiemTraChungChis_KhoaHocs_MaKhoaHoc" FOREIGN KEY ("MaKhoaHoc") REFERENCES public."KhoaHocs"("MaKhoaHoc") not valid;

alter table "public"."KetQuaKiemTraChungChis" validate constraint "FK_KetQuaKiemTraChungChis_KhoaHocs_MaKhoaHoc";

alter table "public"."KetQuaKiemTraChungChis" add constraint "FK_KetQuaKiemTraChungChis_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."KetQuaKiemTraChungChis" validate constraint "FK_KetQuaKiemTraChungChis_NguoiDungs_MaNguoiDung";

alter table "public"."KetQuaLamBais" add constraint "FK_KetQuaLamBais_BaiTaps_MaBaiTap" FOREIGN KEY ("MaBaiTap") REFERENCES public."BaiTaps"("MaBaiTap") not valid;

alter table "public"."KetQuaLamBais" validate constraint "FK_KetQuaLamBais_BaiTaps_MaBaiTap";

alter table "public"."KetQuaLamBais" add constraint "FK_KetQuaLamBais_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."KetQuaLamBais" validate constraint "FK_KetQuaLamBais_NguoiDungs_MaNguoiDung";

alter table "public"."KhoaHocs" add constraint "CK_KhoaHocs_GiaKhoaHoc_Range" CHECK ((("GiaKhoaHoc" >= (10000)::numeric) AND ("GiaKhoaHoc" <= (15000)::numeric))) not valid;

alter table "public"."KhoaHocs" validate constraint "CK_KhoaHocs_GiaKhoaHoc_Range";

alter table "public"."KhoaHocs" add constraint "FK_KhoaHocs_NguoiDungs_MaGiangVien" FOREIGN KEY ("MaGiangVien") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."KhoaHocs" validate constraint "FK_KhoaHocs_NguoiDungs_MaGiangVien";

alter table "public"."LoTrinhAIs" add constraint "FK_LoTrinhAIs_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."LoTrinhAIs" validate constraint "FK_LoTrinhAIs_NguoiDungs_MaNguoiDung";

alter table "public"."MaGiamGiaKhoaHocs" add constraint "FK_MaGiamGiaKhoaHocs_KhoaHocs_MaKhoaHoc" FOREIGN KEY ("MaKhoaHoc") REFERENCES public."KhoaHocs"("MaKhoaHoc") not valid;

alter table "public"."MaGiamGiaKhoaHocs" validate constraint "FK_MaGiamGiaKhoaHocs_KhoaHocs_MaKhoaHoc";

alter table "public"."MaGiamGiaKhoaHocs" add constraint "FK_MaGiamGiaKhoaHocs_MaGiamGias_MaVoucher" FOREIGN KEY ("MaVoucher") REFERENCES public."MaGiamGias"("MaVoucher") ON DELETE CASCADE not valid;

alter table "public"."MaGiamGiaKhoaHocs" validate constraint "FK_MaGiamGiaKhoaHocs_MaGiamGias_MaVoucher";

alter table "public"."MaGiamGias" add constraint "FK_MaGiamGias_NguoiDungs_MaNguoiTao" FOREIGN KEY ("MaNguoiTao") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."MaGiamGias" validate constraint "FK_MaGiamGias_NguoiDungs_MaNguoiTao";

alter table "public"."MaQuaTangHocViens" add constraint "FK_MaQuaTangHocViens_DonHangKhoaHocs_MaDonHang" FOREIGN KEY ("MaDonHang") REFERENCES public."DonHangKhoaHocs"("MaDonHang") ON DELETE CASCADE not valid;

alter table "public"."MaQuaTangHocViens" validate constraint "FK_MaQuaTangHocViens_DonHangKhoaHocs_MaDonHang";

alter table "public"."MaQuaTangHocViens" add constraint "FK_MaQuaTangHocViens_KhoaHocs_MaKhoaHoc" FOREIGN KEY ("MaKhoaHoc") REFERENCES public."KhoaHocs"("MaKhoaHoc") not valid;

alter table "public"."MaQuaTangHocViens" validate constraint "FK_MaQuaTangHocViens_KhoaHocs_MaKhoaHoc";

alter table "public"."MaQuaTangHocViens" add constraint "FK_MaQuaTangHocViens_NguoiDungs_MaNguoiNhan" FOREIGN KEY ("MaNguoiNhan") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."MaQuaTangHocViens" validate constraint "FK_MaQuaTangHocViens_NguoiDungs_MaNguoiNhan";

alter table "public"."MaQuaTangHocViens" add constraint "FK_MaQuaTangHocViens_NguoiDungs_MaNguoiTang" FOREIGN KEY ("MaNguoiTang") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."MaQuaTangHocViens" validate constraint "FK_MaQuaTangHocViens_NguoiDungs_MaNguoiTang";

alter table "public"."NhatKySuDungs" add constraint "FK_NhatKySuDungs_KeyAPIs_ID_Key" FOREIGN KEY ("ID_Key") REFERENCES public."KeyAPIs"("ID") ON DELETE CASCADE not valid;

alter table "public"."NhatKySuDungs" validate constraint "FK_NhatKySuDungs_KeyAPIs_ID_Key";

alter table "public"."PhienDangNhap" add constraint "FK_PhienDangNhap_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") ON DELETE CASCADE not valid;

alter table "public"."PhienDangNhap" validate constraint "FK_PhienDangNhap_NguoiDungs_MaNguoiDung";

alter table "public"."QuaTangKhoaHocs" add constraint "FK_QuaTangKhoaHocs_KhoaHocs_MaKhoaHoc" FOREIGN KEY ("MaKhoaHoc") REFERENCES public."KhoaHocs"("MaKhoaHoc") not valid;

alter table "public"."QuaTangKhoaHocs" validate constraint "FK_QuaTangKhoaHocs_KhoaHocs_MaKhoaHoc";

alter table "public"."QuaTangKhoaHocs" add constraint "FK_QuaTangKhoaHocs_NguoiDungs_MaNguoiNhan" FOREIGN KEY ("MaNguoiNhan") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."QuaTangKhoaHocs" validate constraint "FK_QuaTangKhoaHocs_NguoiDungs_MaNguoiNhan";

alter table "public"."QuaTangKhoaHocs" add constraint "FK_QuaTangKhoaHocs_NguoiDungs_MaNguoiTang" FOREIGN KEY ("MaNguoiTang") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."QuaTangKhoaHocs" validate constraint "FK_QuaTangKhoaHocs_NguoiDungs_MaNguoiTang";

alter table "public"."TestCaseThucHanhs" add constraint "FK_TestCaseThucHanhs_BaiTapThucHanhs_MaBaiTapThucHanh" FOREIGN KEY ("MaBaiTapThucHanh") REFERENCES public."BaiTapThucHanhs"("MaBaiTapTH") ON DELETE CASCADE not valid;

alter table "public"."TestCaseThucHanhs" validate constraint "FK_TestCaseThucHanhs_BaiTapThucHanhs_MaBaiTapThucHanh";

alter table "public"."ThongBaoEmailThanhToans" add constraint "FK_ThongBaoEmailThanhToans_DonHangKhoaHocs_MaDonHang" FOREIGN KEY ("MaDonHang") REFERENCES public."DonHangKhoaHocs"("MaDonHang") ON DELETE CASCADE not valid;

alter table "public"."ThongBaoEmailThanhToans" validate constraint "FK_ThongBaoEmailThanhToans_DonHangKhoaHocs_MaDonHang";

alter table "public"."TienDoBaiHocs" add constraint "FK_TienDoBaiHocs_BaiHocs_MaBaiHoc" FOREIGN KEY ("MaBaiHoc") REFERENCES public."BaiHocs"("MaBaiHoc") not valid;

alter table "public"."TienDoBaiHocs" validate constraint "FK_TienDoBaiHocs_BaiHocs_MaBaiHoc";

alter table "public"."TienDoBaiHocs" add constraint "FK_TienDoBaiHocs_NguoiDungs_MaNguoiDung" FOREIGN KEY ("MaNguoiDung") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."TienDoBaiHocs" validate constraint "FK_TienDoBaiHocs_NguoiDungs_MaNguoiDung";

alter table "public"."VideoChapters" add constraint "FK_VideoChapters_BaiHocs_MaBaiHoc" FOREIGN KEY ("MaBaiHoc") REFERENCES public."BaiHocs"("MaBaiHoc") ON DELETE CASCADE not valid;

alter table "public"."VideoChapters" validate constraint "FK_VideoChapters_BaiHocs_MaBaiHoc";

alter table "public"."VideoQuizs" add constraint "FK_VideoQuizs_VideoChapters_MaChapter" FOREIGN KEY ("MaChapter") REFERENCES public."VideoChapters"("MaChapter") ON DELETE CASCADE not valid;

alter table "public"."VideoQuizs" validate constraint "FK_VideoQuizs_VideoChapters_MaChapter";

alter table "public"."YeuCauRutTienGiangViens" add constraint "CK_YeuCauRutTienGiangVien_SoTienYeuCau_Duong" CHECK (("SoTienYeuCau" > (0)::numeric)) not valid;

alter table "public"."YeuCauRutTienGiangViens" validate constraint "CK_YeuCauRutTienGiangVien_SoTienYeuCau_Duong";

alter table "public"."YeuCauRutTienGiangViens" add constraint "FK_YeuCauRutTienGiangViens_NguoiDungs_MaGiangVien" FOREIGN KEY ("MaGiangVien") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."YeuCauRutTienGiangViens" validate constraint "FK_YeuCauRutTienGiangViens_NguoiDungs_MaGiangVien";

alter table "public"."YeuCauRutTienGiangViens" add constraint "FK_YeuCauRutTienGiangViens_NguoiDungs_MaQuanTriVienDuyet" FOREIGN KEY ("MaQuanTriVienDuyet") REFERENCES public."NguoiDungs"("MaNguoiDung") not valid;

alter table "public"."YeuCauRutTienGiangViens" validate constraint "FK_YeuCauRutTienGiangViens_NguoiDungs_MaQuanTriVienDuyet";

grant delete on table "public"."ApiKeyAuditLogs" to "anon";

grant insert on table "public"."ApiKeyAuditLogs" to "anon";

grant references on table "public"."ApiKeyAuditLogs" to "anon";

grant select on table "public"."ApiKeyAuditLogs" to "anon";

grant trigger on table "public"."ApiKeyAuditLogs" to "anon";

grant truncate on table "public"."ApiKeyAuditLogs" to "anon";

grant update on table "public"."ApiKeyAuditLogs" to "anon";

grant delete on table "public"."ApiKeyAuditLogs" to "authenticated";

grant insert on table "public"."ApiKeyAuditLogs" to "authenticated";

grant references on table "public"."ApiKeyAuditLogs" to "authenticated";

grant select on table "public"."ApiKeyAuditLogs" to "authenticated";

grant trigger on table "public"."ApiKeyAuditLogs" to "authenticated";

grant truncate on table "public"."ApiKeyAuditLogs" to "authenticated";

grant update on table "public"."ApiKeyAuditLogs" to "authenticated";

grant delete on table "public"."ApiKeyAuditLogs" to "service_role";

grant insert on table "public"."ApiKeyAuditLogs" to "service_role";

grant references on table "public"."ApiKeyAuditLogs" to "service_role";

grant select on table "public"."ApiKeyAuditLogs" to "service_role";

grant trigger on table "public"."ApiKeyAuditLogs" to "service_role";

grant truncate on table "public"."ApiKeyAuditLogs" to "service_role";

grant update on table "public"."ApiKeyAuditLogs" to "service_role";

grant delete on table "public"."BaiHocs" to "anon";

grant insert on table "public"."BaiHocs" to "anon";

grant references on table "public"."BaiHocs" to "anon";

grant select on table "public"."BaiHocs" to "anon";

grant trigger on table "public"."BaiHocs" to "anon";

grant truncate on table "public"."BaiHocs" to "anon";

grant update on table "public"."BaiHocs" to "anon";

grant delete on table "public"."BaiHocs" to "authenticated";

grant insert on table "public"."BaiHocs" to "authenticated";

grant references on table "public"."BaiHocs" to "authenticated";

grant select on table "public"."BaiHocs" to "authenticated";

grant trigger on table "public"."BaiHocs" to "authenticated";

grant truncate on table "public"."BaiHocs" to "authenticated";

grant update on table "public"."BaiHocs" to "authenticated";

grant delete on table "public"."BaiHocs" to "service_role";

grant insert on table "public"."BaiHocs" to "service_role";

grant references on table "public"."BaiHocs" to "service_role";

grant select on table "public"."BaiHocs" to "service_role";

grant trigger on table "public"."BaiHocs" to "service_role";

grant truncate on table "public"."BaiHocs" to "service_role";

grant update on table "public"."BaiHocs" to "service_role";

grant delete on table "public"."BaiTapThucHanhs" to "anon";

grant insert on table "public"."BaiTapThucHanhs" to "anon";

grant references on table "public"."BaiTapThucHanhs" to "anon";

grant select on table "public"."BaiTapThucHanhs" to "anon";

grant trigger on table "public"."BaiTapThucHanhs" to "anon";

grant truncate on table "public"."BaiTapThucHanhs" to "anon";

grant update on table "public"."BaiTapThucHanhs" to "anon";

grant delete on table "public"."BaiTapThucHanhs" to "authenticated";

grant insert on table "public"."BaiTapThucHanhs" to "authenticated";

grant references on table "public"."BaiTapThucHanhs" to "authenticated";

grant select on table "public"."BaiTapThucHanhs" to "authenticated";

grant trigger on table "public"."BaiTapThucHanhs" to "authenticated";

grant truncate on table "public"."BaiTapThucHanhs" to "authenticated";

grant update on table "public"."BaiTapThucHanhs" to "authenticated";

grant delete on table "public"."BaiTapThucHanhs" to "service_role";

grant insert on table "public"."BaiTapThucHanhs" to "service_role";

grant references on table "public"."BaiTapThucHanhs" to "service_role";

grant select on table "public"."BaiTapThucHanhs" to "service_role";

grant trigger on table "public"."BaiTapThucHanhs" to "service_role";

grant truncate on table "public"."BaiTapThucHanhs" to "service_role";

grant update on table "public"."BaiTapThucHanhs" to "service_role";

grant delete on table "public"."BaiTap_Quizs" to "anon";

grant insert on table "public"."BaiTap_Quizs" to "anon";

grant references on table "public"."BaiTap_Quizs" to "anon";

grant select on table "public"."BaiTap_Quizs" to "anon";

grant trigger on table "public"."BaiTap_Quizs" to "anon";

grant truncate on table "public"."BaiTap_Quizs" to "anon";

grant update on table "public"."BaiTap_Quizs" to "anon";

grant delete on table "public"."BaiTap_Quizs" to "authenticated";

grant insert on table "public"."BaiTap_Quizs" to "authenticated";

grant references on table "public"."BaiTap_Quizs" to "authenticated";

grant select on table "public"."BaiTap_Quizs" to "authenticated";

grant trigger on table "public"."BaiTap_Quizs" to "authenticated";

grant truncate on table "public"."BaiTap_Quizs" to "authenticated";

grant update on table "public"."BaiTap_Quizs" to "authenticated";

grant delete on table "public"."BaiTap_Quizs" to "service_role";

grant insert on table "public"."BaiTap_Quizs" to "service_role";

grant references on table "public"."BaiTap_Quizs" to "service_role";

grant select on table "public"."BaiTap_Quizs" to "service_role";

grant trigger on table "public"."BaiTap_Quizs" to "service_role";

grant truncate on table "public"."BaiTap_Quizs" to "service_role";

grant update on table "public"."BaiTap_Quizs" to "service_role";

grant delete on table "public"."BaiTaps" to "anon";

grant insert on table "public"."BaiTaps" to "anon";

grant references on table "public"."BaiTaps" to "anon";

grant select on table "public"."BaiTaps" to "anon";

grant trigger on table "public"."BaiTaps" to "anon";

grant truncate on table "public"."BaiTaps" to "anon";

grant update on table "public"."BaiTaps" to "anon";

grant delete on table "public"."BaiTaps" to "authenticated";

grant insert on table "public"."BaiTaps" to "authenticated";

grant references on table "public"."BaiTaps" to "authenticated";

grant select on table "public"."BaiTaps" to "authenticated";

grant trigger on table "public"."BaiTaps" to "authenticated";

grant truncate on table "public"."BaiTaps" to "authenticated";

grant update on table "public"."BaiTaps" to "authenticated";

grant delete on table "public"."BaiTaps" to "service_role";

grant insert on table "public"."BaiTaps" to "service_role";

grant references on table "public"."BaiTaps" to "service_role";

grant select on table "public"."BaiTaps" to "service_role";

grant trigger on table "public"."BaiTaps" to "service_role";

grant truncate on table "public"."BaiTaps" to "service_role";

grant update on table "public"."BaiTaps" to "service_role";

grant delete on table "public"."BinhLuans" to "anon";

grant insert on table "public"."BinhLuans" to "anon";

grant references on table "public"."BinhLuans" to "anon";

grant select on table "public"."BinhLuans" to "anon";

grant trigger on table "public"."BinhLuans" to "anon";

grant truncate on table "public"."BinhLuans" to "anon";

grant update on table "public"."BinhLuans" to "anon";

grant delete on table "public"."BinhLuans" to "authenticated";

grant insert on table "public"."BinhLuans" to "authenticated";

grant references on table "public"."BinhLuans" to "authenticated";

grant select on table "public"."BinhLuans" to "authenticated";

grant trigger on table "public"."BinhLuans" to "authenticated";

grant truncate on table "public"."BinhLuans" to "authenticated";

grant update on table "public"."BinhLuans" to "authenticated";

grant delete on table "public"."BinhLuans" to "service_role";

grant insert on table "public"."BinhLuans" to "service_role";

grant references on table "public"."BinhLuans" to "service_role";

grant select on table "public"."BinhLuans" to "service_role";

grant trigger on table "public"."BinhLuans" to "service_role";

grant truncate on table "public"."BinhLuans" to "service_role";

grant update on table "public"."BinhLuans" to "service_role";

grant delete on table "public"."CauHinhs" to "anon";

grant insert on table "public"."CauHinhs" to "anon";

grant references on table "public"."CauHinhs" to "anon";

grant select on table "public"."CauHinhs" to "anon";

grant trigger on table "public"."CauHinhs" to "anon";

grant truncate on table "public"."CauHinhs" to "anon";

grant update on table "public"."CauHinhs" to "anon";

grant delete on table "public"."CauHinhs" to "authenticated";

grant insert on table "public"."CauHinhs" to "authenticated";

grant references on table "public"."CauHinhs" to "authenticated";

grant select on table "public"."CauHinhs" to "authenticated";

grant trigger on table "public"."CauHinhs" to "authenticated";

grant truncate on table "public"."CauHinhs" to "authenticated";

grant update on table "public"."CauHinhs" to "authenticated";

grant delete on table "public"."CauHinhs" to "service_role";

grant insert on table "public"."CauHinhs" to "service_role";

grant references on table "public"."CauHinhs" to "service_role";

grant select on table "public"."CauHinhs" to "service_role";

grant trigger on table "public"."CauHinhs" to "service_role";

grant truncate on table "public"."CauHinhs" to "service_role";

grant update on table "public"."CauHinhs" to "service_role";

grant delete on table "public"."ChiTietDonHangs" to "anon";

grant insert on table "public"."ChiTietDonHangs" to "anon";

grant references on table "public"."ChiTietDonHangs" to "anon";

grant select on table "public"."ChiTietDonHangs" to "anon";

grant trigger on table "public"."ChiTietDonHangs" to "anon";

grant truncate on table "public"."ChiTietDonHangs" to "anon";

grant update on table "public"."ChiTietDonHangs" to "anon";

grant delete on table "public"."ChiTietDonHangs" to "authenticated";

grant insert on table "public"."ChiTietDonHangs" to "authenticated";

grant references on table "public"."ChiTietDonHangs" to "authenticated";

grant select on table "public"."ChiTietDonHangs" to "authenticated";

grant trigger on table "public"."ChiTietDonHangs" to "authenticated";

grant truncate on table "public"."ChiTietDonHangs" to "authenticated";

grant update on table "public"."ChiTietDonHangs" to "authenticated";

grant delete on table "public"."ChiTietDonHangs" to "service_role";

grant insert on table "public"."ChiTietDonHangs" to "service_role";

grant references on table "public"."ChiTietDonHangs" to "service_role";

grant select on table "public"."ChiTietDonHangs" to "service_role";

grant trigger on table "public"."ChiTietDonHangs" to "service_role";

grant truncate on table "public"."ChiTietDonHangs" to "service_role";

grant update on table "public"."ChiTietDonHangs" to "service_role";

grant delete on table "public"."ChungChiKhoaHocs" to "anon";

grant insert on table "public"."ChungChiKhoaHocs" to "anon";

grant references on table "public"."ChungChiKhoaHocs" to "anon";

grant select on table "public"."ChungChiKhoaHocs" to "anon";

grant trigger on table "public"."ChungChiKhoaHocs" to "anon";

grant truncate on table "public"."ChungChiKhoaHocs" to "anon";

grant update on table "public"."ChungChiKhoaHocs" to "anon";

grant delete on table "public"."ChungChiKhoaHocs" to "authenticated";

grant insert on table "public"."ChungChiKhoaHocs" to "authenticated";

grant references on table "public"."ChungChiKhoaHocs" to "authenticated";

grant select on table "public"."ChungChiKhoaHocs" to "authenticated";

grant trigger on table "public"."ChungChiKhoaHocs" to "authenticated";

grant truncate on table "public"."ChungChiKhoaHocs" to "authenticated";

grant update on table "public"."ChungChiKhoaHocs" to "authenticated";

grant delete on table "public"."ChungChiKhoaHocs" to "service_role";

grant insert on table "public"."ChungChiKhoaHocs" to "service_role";

grant references on table "public"."ChungChiKhoaHocs" to "service_role";

grant select on table "public"."ChungChiKhoaHocs" to "service_role";

grant trigger on table "public"."ChungChiKhoaHocs" to "service_role";

grant truncate on table "public"."ChungChiKhoaHocs" to "service_role";

grant update on table "public"."ChungChiKhoaHocs" to "service_role";

grant delete on table "public"."ChuongHocs" to "anon";

grant insert on table "public"."ChuongHocs" to "anon";

grant references on table "public"."ChuongHocs" to "anon";

grant select on table "public"."ChuongHocs" to "anon";

grant trigger on table "public"."ChuongHocs" to "anon";

grant truncate on table "public"."ChuongHocs" to "anon";

grant update on table "public"."ChuongHocs" to "anon";

grant delete on table "public"."ChuongHocs" to "authenticated";

grant insert on table "public"."ChuongHocs" to "authenticated";

grant references on table "public"."ChuongHocs" to "authenticated";

grant select on table "public"."ChuongHocs" to "authenticated";

grant trigger on table "public"."ChuongHocs" to "authenticated";

grant truncate on table "public"."ChuongHocs" to "authenticated";

grant update on table "public"."ChuongHocs" to "authenticated";

grant delete on table "public"."ChuongHocs" to "service_role";

grant insert on table "public"."ChuongHocs" to "service_role";

grant references on table "public"."ChuongHocs" to "service_role";

grant select on table "public"."ChuongHocs" to "service_role";

grant trigger on table "public"."ChuongHocs" to "service_role";

grant truncate on table "public"."ChuongHocs" to "service_role";

grant update on table "public"."ChuongHocs" to "service_role";

grant delete on table "public"."DangKyKhoaHocs" to "anon";

grant insert on table "public"."DangKyKhoaHocs" to "anon";

grant references on table "public"."DangKyKhoaHocs" to "anon";

grant select on table "public"."DangKyKhoaHocs" to "anon";

grant trigger on table "public"."DangKyKhoaHocs" to "anon";

grant truncate on table "public"."DangKyKhoaHocs" to "anon";

grant update on table "public"."DangKyKhoaHocs" to "anon";

grant delete on table "public"."DangKyKhoaHocs" to "authenticated";

grant insert on table "public"."DangKyKhoaHocs" to "authenticated";

grant references on table "public"."DangKyKhoaHocs" to "authenticated";

grant select on table "public"."DangKyKhoaHocs" to "authenticated";

grant trigger on table "public"."DangKyKhoaHocs" to "authenticated";

grant truncate on table "public"."DangKyKhoaHocs" to "authenticated";

grant update on table "public"."DangKyKhoaHocs" to "authenticated";

grant delete on table "public"."DangKyKhoaHocs" to "service_role";

grant insert on table "public"."DangKyKhoaHocs" to "service_role";

grant references on table "public"."DangKyKhoaHocs" to "service_role";

grant select on table "public"."DangKyKhoaHocs" to "service_role";

grant trigger on table "public"."DangKyKhoaHocs" to "service_role";

grant truncate on table "public"."DangKyKhoaHocs" to "service_role";

grant update on table "public"."DangKyKhoaHocs" to "service_role";

grant delete on table "public"."DanhGias" to "anon";

grant insert on table "public"."DanhGias" to "anon";

grant references on table "public"."DanhGias" to "anon";

grant select on table "public"."DanhGias" to "anon";

grant trigger on table "public"."DanhGias" to "anon";

grant truncate on table "public"."DanhGias" to "anon";

grant update on table "public"."DanhGias" to "anon";

grant delete on table "public"."DanhGias" to "authenticated";

grant insert on table "public"."DanhGias" to "authenticated";

grant references on table "public"."DanhGias" to "authenticated";

grant select on table "public"."DanhGias" to "authenticated";

grant trigger on table "public"."DanhGias" to "authenticated";

grant truncate on table "public"."DanhGias" to "authenticated";

grant update on table "public"."DanhGias" to "authenticated";

grant delete on table "public"."DanhGias" to "service_role";

grant insert on table "public"."DanhGias" to "service_role";

grant references on table "public"."DanhGias" to "service_role";

grant select on table "public"."DanhGias" to "service_role";

grant trigger on table "public"."DanhGias" to "service_role";

grant truncate on table "public"."DanhGias" to "service_role";

grant update on table "public"."DanhGias" to "service_role";

grant delete on table "public"."DoanhThuGiangViens" to "anon";

grant insert on table "public"."DoanhThuGiangViens" to "anon";

grant references on table "public"."DoanhThuGiangViens" to "anon";

grant select on table "public"."DoanhThuGiangViens" to "anon";

grant trigger on table "public"."DoanhThuGiangViens" to "anon";

grant truncate on table "public"."DoanhThuGiangViens" to "anon";

grant update on table "public"."DoanhThuGiangViens" to "anon";

grant delete on table "public"."DoanhThuGiangViens" to "authenticated";

grant insert on table "public"."DoanhThuGiangViens" to "authenticated";

grant references on table "public"."DoanhThuGiangViens" to "authenticated";

grant select on table "public"."DoanhThuGiangViens" to "authenticated";

grant trigger on table "public"."DoanhThuGiangViens" to "authenticated";

grant truncate on table "public"."DoanhThuGiangViens" to "authenticated";

grant update on table "public"."DoanhThuGiangViens" to "authenticated";

grant delete on table "public"."DoanhThuGiangViens" to "service_role";

grant insert on table "public"."DoanhThuGiangViens" to "service_role";

grant references on table "public"."DoanhThuGiangViens" to "service_role";

grant select on table "public"."DoanhThuGiangViens" to "service_role";

grant trigger on table "public"."DoanhThuGiangViens" to "service_role";

grant truncate on table "public"."DoanhThuGiangViens" to "service_role";

grant update on table "public"."DoanhThuGiangViens" to "service_role";

grant delete on table "public"."DonHangKhoaHocs" to "anon";

grant insert on table "public"."DonHangKhoaHocs" to "anon";

grant references on table "public"."DonHangKhoaHocs" to "anon";

grant select on table "public"."DonHangKhoaHocs" to "anon";

grant trigger on table "public"."DonHangKhoaHocs" to "anon";

grant truncate on table "public"."DonHangKhoaHocs" to "anon";

grant update on table "public"."DonHangKhoaHocs" to "anon";

grant delete on table "public"."DonHangKhoaHocs" to "authenticated";

grant insert on table "public"."DonHangKhoaHocs" to "authenticated";

grant references on table "public"."DonHangKhoaHocs" to "authenticated";

grant select on table "public"."DonHangKhoaHocs" to "authenticated";

grant trigger on table "public"."DonHangKhoaHocs" to "authenticated";

grant truncate on table "public"."DonHangKhoaHocs" to "authenticated";

grant update on table "public"."DonHangKhoaHocs" to "authenticated";

grant delete on table "public"."DonHangKhoaHocs" to "service_role";

grant insert on table "public"."DonHangKhoaHocs" to "service_role";

grant references on table "public"."DonHangKhoaHocs" to "service_role";

grant select on table "public"."DonHangKhoaHocs" to "service_role";

grant trigger on table "public"."DonHangKhoaHocs" to "service_role";

grant truncate on table "public"."DonHangKhoaHocs" to "service_role";

grant update on table "public"."DonHangKhoaHocs" to "service_role";

grant delete on table "public"."GhiChuAIs" to "anon";

grant insert on table "public"."GhiChuAIs" to "anon";

grant references on table "public"."GhiChuAIs" to "anon";

grant select on table "public"."GhiChuAIs" to "anon";

grant trigger on table "public"."GhiChuAIs" to "anon";

grant truncate on table "public"."GhiChuAIs" to "anon";

grant update on table "public"."GhiChuAIs" to "anon";

grant delete on table "public"."GhiChuAIs" to "authenticated";

grant insert on table "public"."GhiChuAIs" to "authenticated";

grant references on table "public"."GhiChuAIs" to "authenticated";

grant select on table "public"."GhiChuAIs" to "authenticated";

grant trigger on table "public"."GhiChuAIs" to "authenticated";

grant truncate on table "public"."GhiChuAIs" to "authenticated";

grant update on table "public"."GhiChuAIs" to "authenticated";

grant delete on table "public"."GhiChuAIs" to "service_role";

grant insert on table "public"."GhiChuAIs" to "service_role";

grant references on table "public"."GhiChuAIs" to "service_role";

grant select on table "public"."GhiChuAIs" to "service_role";

grant trigger on table "public"."GhiChuAIs" to "service_role";

grant truncate on table "public"."GhiChuAIs" to "service_role";

grant update on table "public"."GhiChuAIs" to "service_role";

grant delete on table "public"."GhiChuBaiHocs" to "anon";

grant insert on table "public"."GhiChuBaiHocs" to "anon";

grant references on table "public"."GhiChuBaiHocs" to "anon";

grant select on table "public"."GhiChuBaiHocs" to "anon";

grant trigger on table "public"."GhiChuBaiHocs" to "anon";

grant truncate on table "public"."GhiChuBaiHocs" to "anon";

grant update on table "public"."GhiChuBaiHocs" to "anon";

grant delete on table "public"."GhiChuBaiHocs" to "authenticated";

grant insert on table "public"."GhiChuBaiHocs" to "authenticated";

grant references on table "public"."GhiChuBaiHocs" to "authenticated";

grant select on table "public"."GhiChuBaiHocs" to "authenticated";

grant trigger on table "public"."GhiChuBaiHocs" to "authenticated";

grant truncate on table "public"."GhiChuBaiHocs" to "authenticated";

grant update on table "public"."GhiChuBaiHocs" to "authenticated";

grant delete on table "public"."GhiChuBaiHocs" to "service_role";

grant insert on table "public"."GhiChuBaiHocs" to "service_role";

grant references on table "public"."GhiChuBaiHocs" to "service_role";

grant select on table "public"."GhiChuBaiHocs" to "service_role";

grant trigger on table "public"."GhiChuBaiHocs" to "service_role";

grant truncate on table "public"."GhiChuBaiHocs" to "service_role";

grant update on table "public"."GhiChuBaiHocs" to "service_role";

grant delete on table "public"."GiaoDichThanhToans" to "anon";

grant insert on table "public"."GiaoDichThanhToans" to "anon";

grant references on table "public"."GiaoDichThanhToans" to "anon";

grant select on table "public"."GiaoDichThanhToans" to "anon";

grant trigger on table "public"."GiaoDichThanhToans" to "anon";

grant truncate on table "public"."GiaoDichThanhToans" to "anon";

grant update on table "public"."GiaoDichThanhToans" to "anon";

grant delete on table "public"."GiaoDichThanhToans" to "authenticated";

grant insert on table "public"."GiaoDichThanhToans" to "authenticated";

grant references on table "public"."GiaoDichThanhToans" to "authenticated";

grant select on table "public"."GiaoDichThanhToans" to "authenticated";

grant trigger on table "public"."GiaoDichThanhToans" to "authenticated";

grant truncate on table "public"."GiaoDichThanhToans" to "authenticated";

grant update on table "public"."GiaoDichThanhToans" to "authenticated";

grant delete on table "public"."GiaoDichThanhToans" to "service_role";

grant insert on table "public"."GiaoDichThanhToans" to "service_role";

grant references on table "public"."GiaoDichThanhToans" to "service_role";

grant select on table "public"."GiaoDichThanhToans" to "service_role";

grant trigger on table "public"."GiaoDichThanhToans" to "service_role";

grant truncate on table "public"."GiaoDichThanhToans" to "service_role";

grant update on table "public"."GiaoDichThanhToans" to "service_role";

grant delete on table "public"."HoTroRutTienGiangViens" to "anon";

grant insert on table "public"."HoTroRutTienGiangViens" to "anon";

grant references on table "public"."HoTroRutTienGiangViens" to "anon";

grant select on table "public"."HoTroRutTienGiangViens" to "anon";

grant trigger on table "public"."HoTroRutTienGiangViens" to "anon";

grant truncate on table "public"."HoTroRutTienGiangViens" to "anon";

grant update on table "public"."HoTroRutTienGiangViens" to "anon";

grant delete on table "public"."HoTroRutTienGiangViens" to "authenticated";

grant insert on table "public"."HoTroRutTienGiangViens" to "authenticated";

grant references on table "public"."HoTroRutTienGiangViens" to "authenticated";

grant select on table "public"."HoTroRutTienGiangViens" to "authenticated";

grant trigger on table "public"."HoTroRutTienGiangViens" to "authenticated";

grant truncate on table "public"."HoTroRutTienGiangViens" to "authenticated";

grant update on table "public"."HoTroRutTienGiangViens" to "authenticated";

grant delete on table "public"."HoTroRutTienGiangViens" to "service_role";

grant insert on table "public"."HoTroRutTienGiangViens" to "service_role";

grant references on table "public"."HoTroRutTienGiangViens" to "service_role";

grant select on table "public"."HoTroRutTienGiangViens" to "service_role";

grant trigger on table "public"."HoTroRutTienGiangViens" to "service_role";

grant truncate on table "public"."HoTroRutTienGiangViens" to "service_role";

grant update on table "public"."HoTroRutTienGiangViens" to "service_role";

grant delete on table "public"."KetQuaKiemTraChungChis" to "anon";

grant insert on table "public"."KetQuaKiemTraChungChis" to "anon";

grant references on table "public"."KetQuaKiemTraChungChis" to "anon";

grant select on table "public"."KetQuaKiemTraChungChis" to "anon";

grant trigger on table "public"."KetQuaKiemTraChungChis" to "anon";

grant truncate on table "public"."KetQuaKiemTraChungChis" to "anon";

grant update on table "public"."KetQuaKiemTraChungChis" to "anon";

grant delete on table "public"."KetQuaKiemTraChungChis" to "authenticated";

grant insert on table "public"."KetQuaKiemTraChungChis" to "authenticated";

grant references on table "public"."KetQuaKiemTraChungChis" to "authenticated";

grant select on table "public"."KetQuaKiemTraChungChis" to "authenticated";

grant trigger on table "public"."KetQuaKiemTraChungChis" to "authenticated";

grant truncate on table "public"."KetQuaKiemTraChungChis" to "authenticated";

grant update on table "public"."KetQuaKiemTraChungChis" to "authenticated";

grant delete on table "public"."KetQuaKiemTraChungChis" to "service_role";

grant insert on table "public"."KetQuaKiemTraChungChis" to "service_role";

grant references on table "public"."KetQuaKiemTraChungChis" to "service_role";

grant select on table "public"."KetQuaKiemTraChungChis" to "service_role";

grant trigger on table "public"."KetQuaKiemTraChungChis" to "service_role";

grant truncate on table "public"."KetQuaKiemTraChungChis" to "service_role";

grant update on table "public"."KetQuaKiemTraChungChis" to "service_role";

grant delete on table "public"."KetQuaLamBais" to "anon";

grant insert on table "public"."KetQuaLamBais" to "anon";

grant references on table "public"."KetQuaLamBais" to "anon";

grant select on table "public"."KetQuaLamBais" to "anon";

grant trigger on table "public"."KetQuaLamBais" to "anon";

grant truncate on table "public"."KetQuaLamBais" to "anon";

grant update on table "public"."KetQuaLamBais" to "anon";

grant delete on table "public"."KetQuaLamBais" to "authenticated";

grant insert on table "public"."KetQuaLamBais" to "authenticated";

grant references on table "public"."KetQuaLamBais" to "authenticated";

grant select on table "public"."KetQuaLamBais" to "authenticated";

grant trigger on table "public"."KetQuaLamBais" to "authenticated";

grant truncate on table "public"."KetQuaLamBais" to "authenticated";

grant update on table "public"."KetQuaLamBais" to "authenticated";

grant delete on table "public"."KetQuaLamBais" to "service_role";

grant insert on table "public"."KetQuaLamBais" to "service_role";

grant references on table "public"."KetQuaLamBais" to "service_role";

grant select on table "public"."KetQuaLamBais" to "service_role";

grant trigger on table "public"."KetQuaLamBais" to "service_role";

grant truncate on table "public"."KetQuaLamBais" to "service_role";

grant update on table "public"."KetQuaLamBais" to "service_role";

grant delete on table "public"."KeyAPIs" to "anon";

grant insert on table "public"."KeyAPIs" to "anon";

grant references on table "public"."KeyAPIs" to "anon";

grant select on table "public"."KeyAPIs" to "anon";

grant trigger on table "public"."KeyAPIs" to "anon";

grant truncate on table "public"."KeyAPIs" to "anon";

grant update on table "public"."KeyAPIs" to "anon";

grant delete on table "public"."KeyAPIs" to "authenticated";

grant insert on table "public"."KeyAPIs" to "authenticated";

grant references on table "public"."KeyAPIs" to "authenticated";

grant select on table "public"."KeyAPIs" to "authenticated";

grant trigger on table "public"."KeyAPIs" to "authenticated";

grant truncate on table "public"."KeyAPIs" to "authenticated";

grant update on table "public"."KeyAPIs" to "authenticated";

grant delete on table "public"."KeyAPIs" to "service_role";

grant insert on table "public"."KeyAPIs" to "service_role";

grant references on table "public"."KeyAPIs" to "service_role";

grant select on table "public"."KeyAPIs" to "service_role";

grant trigger on table "public"."KeyAPIs" to "service_role";

grant truncate on table "public"."KeyAPIs" to "service_role";

grant update on table "public"."KeyAPIs" to "service_role";

grant delete on table "public"."KhoaHocs" to "anon";

grant insert on table "public"."KhoaHocs" to "anon";

grant references on table "public"."KhoaHocs" to "anon";

grant select on table "public"."KhoaHocs" to "anon";

grant trigger on table "public"."KhoaHocs" to "anon";

grant truncate on table "public"."KhoaHocs" to "anon";

grant update on table "public"."KhoaHocs" to "anon";

grant delete on table "public"."KhoaHocs" to "authenticated";

grant insert on table "public"."KhoaHocs" to "authenticated";

grant references on table "public"."KhoaHocs" to "authenticated";

grant select on table "public"."KhoaHocs" to "authenticated";

grant trigger on table "public"."KhoaHocs" to "authenticated";

grant truncate on table "public"."KhoaHocs" to "authenticated";

grant update on table "public"."KhoaHocs" to "authenticated";

grant delete on table "public"."KhoaHocs" to "service_role";

grant insert on table "public"."KhoaHocs" to "service_role";

grant references on table "public"."KhoaHocs" to "service_role";

grant select on table "public"."KhoaHocs" to "service_role";

grant trigger on table "public"."KhoaHocs" to "service_role";

grant truncate on table "public"."KhoaHocs" to "service_role";

grant update on table "public"."KhoaHocs" to "service_role";

grant delete on table "public"."LoTrinhAIs" to "anon";

grant insert on table "public"."LoTrinhAIs" to "anon";

grant references on table "public"."LoTrinhAIs" to "anon";

grant select on table "public"."LoTrinhAIs" to "anon";

grant trigger on table "public"."LoTrinhAIs" to "anon";

grant truncate on table "public"."LoTrinhAIs" to "anon";

grant update on table "public"."LoTrinhAIs" to "anon";

grant delete on table "public"."LoTrinhAIs" to "authenticated";

grant insert on table "public"."LoTrinhAIs" to "authenticated";

grant references on table "public"."LoTrinhAIs" to "authenticated";

grant select on table "public"."LoTrinhAIs" to "authenticated";

grant trigger on table "public"."LoTrinhAIs" to "authenticated";

grant truncate on table "public"."LoTrinhAIs" to "authenticated";

grant update on table "public"."LoTrinhAIs" to "authenticated";

grant delete on table "public"."LoTrinhAIs" to "service_role";

grant insert on table "public"."LoTrinhAIs" to "service_role";

grant references on table "public"."LoTrinhAIs" to "service_role";

grant select on table "public"."LoTrinhAIs" to "service_role";

grant trigger on table "public"."LoTrinhAIs" to "service_role";

grant truncate on table "public"."LoTrinhAIs" to "service_role";

grant update on table "public"."LoTrinhAIs" to "service_role";

grant delete on table "public"."MaGiamGiaKhoaHocs" to "anon";

grant insert on table "public"."MaGiamGiaKhoaHocs" to "anon";

grant references on table "public"."MaGiamGiaKhoaHocs" to "anon";

grant select on table "public"."MaGiamGiaKhoaHocs" to "anon";

grant trigger on table "public"."MaGiamGiaKhoaHocs" to "anon";

grant truncate on table "public"."MaGiamGiaKhoaHocs" to "anon";

grant update on table "public"."MaGiamGiaKhoaHocs" to "anon";

grant delete on table "public"."MaGiamGiaKhoaHocs" to "authenticated";

grant insert on table "public"."MaGiamGiaKhoaHocs" to "authenticated";

grant references on table "public"."MaGiamGiaKhoaHocs" to "authenticated";

grant select on table "public"."MaGiamGiaKhoaHocs" to "authenticated";

grant trigger on table "public"."MaGiamGiaKhoaHocs" to "authenticated";

grant truncate on table "public"."MaGiamGiaKhoaHocs" to "authenticated";

grant update on table "public"."MaGiamGiaKhoaHocs" to "authenticated";

grant delete on table "public"."MaGiamGiaKhoaHocs" to "service_role";

grant insert on table "public"."MaGiamGiaKhoaHocs" to "service_role";

grant references on table "public"."MaGiamGiaKhoaHocs" to "service_role";

grant select on table "public"."MaGiamGiaKhoaHocs" to "service_role";

grant trigger on table "public"."MaGiamGiaKhoaHocs" to "service_role";

grant truncate on table "public"."MaGiamGiaKhoaHocs" to "service_role";

grant update on table "public"."MaGiamGiaKhoaHocs" to "service_role";

grant delete on table "public"."MaGiamGias" to "anon";

grant insert on table "public"."MaGiamGias" to "anon";

grant references on table "public"."MaGiamGias" to "anon";

grant select on table "public"."MaGiamGias" to "anon";

grant trigger on table "public"."MaGiamGias" to "anon";

grant truncate on table "public"."MaGiamGias" to "anon";

grant update on table "public"."MaGiamGias" to "anon";

grant delete on table "public"."MaGiamGias" to "authenticated";

grant insert on table "public"."MaGiamGias" to "authenticated";

grant references on table "public"."MaGiamGias" to "authenticated";

grant select on table "public"."MaGiamGias" to "authenticated";

grant trigger on table "public"."MaGiamGias" to "authenticated";

grant truncate on table "public"."MaGiamGias" to "authenticated";

grant update on table "public"."MaGiamGias" to "authenticated";

grant delete on table "public"."MaGiamGias" to "service_role";

grant insert on table "public"."MaGiamGias" to "service_role";

grant references on table "public"."MaGiamGias" to "service_role";

grant select on table "public"."MaGiamGias" to "service_role";

grant trigger on table "public"."MaGiamGias" to "service_role";

grant truncate on table "public"."MaGiamGias" to "service_role";

grant update on table "public"."MaGiamGias" to "service_role";

grant delete on table "public"."MaQuaTangHocViens" to "anon";

grant insert on table "public"."MaQuaTangHocViens" to "anon";

grant references on table "public"."MaQuaTangHocViens" to "anon";

grant select on table "public"."MaQuaTangHocViens" to "anon";

grant trigger on table "public"."MaQuaTangHocViens" to "anon";

grant truncate on table "public"."MaQuaTangHocViens" to "anon";

grant update on table "public"."MaQuaTangHocViens" to "anon";

grant delete on table "public"."MaQuaTangHocViens" to "authenticated";

grant insert on table "public"."MaQuaTangHocViens" to "authenticated";

grant references on table "public"."MaQuaTangHocViens" to "authenticated";

grant select on table "public"."MaQuaTangHocViens" to "authenticated";

grant trigger on table "public"."MaQuaTangHocViens" to "authenticated";

grant truncate on table "public"."MaQuaTangHocViens" to "authenticated";

grant update on table "public"."MaQuaTangHocViens" to "authenticated";

grant delete on table "public"."MaQuaTangHocViens" to "service_role";

grant insert on table "public"."MaQuaTangHocViens" to "service_role";

grant references on table "public"."MaQuaTangHocViens" to "service_role";

grant select on table "public"."MaQuaTangHocViens" to "service_role";

grant trigger on table "public"."MaQuaTangHocViens" to "service_role";

grant truncate on table "public"."MaQuaTangHocViens" to "service_role";

grant update on table "public"."MaQuaTangHocViens" to "service_role";

grant delete on table "public"."NguoiDungs" to "anon";

grant insert on table "public"."NguoiDungs" to "anon";

grant references on table "public"."NguoiDungs" to "anon";

grant select on table "public"."NguoiDungs" to "anon";

grant trigger on table "public"."NguoiDungs" to "anon";

grant truncate on table "public"."NguoiDungs" to "anon";

grant update on table "public"."NguoiDungs" to "anon";

grant delete on table "public"."NguoiDungs" to "authenticated";

grant insert on table "public"."NguoiDungs" to "authenticated";

grant references on table "public"."NguoiDungs" to "authenticated";

grant select on table "public"."NguoiDungs" to "authenticated";

grant trigger on table "public"."NguoiDungs" to "authenticated";

grant truncate on table "public"."NguoiDungs" to "authenticated";

grant update on table "public"."NguoiDungs" to "authenticated";

grant delete on table "public"."NguoiDungs" to "service_role";

grant insert on table "public"."NguoiDungs" to "service_role";

grant references on table "public"."NguoiDungs" to "service_role";

grant select on table "public"."NguoiDungs" to "service_role";

grant trigger on table "public"."NguoiDungs" to "service_role";

grant truncate on table "public"."NguoiDungs" to "service_role";

grant update on table "public"."NguoiDungs" to "service_role";

grant delete on table "public"."NhatKySuDungs" to "anon";

grant insert on table "public"."NhatKySuDungs" to "anon";

grant references on table "public"."NhatKySuDungs" to "anon";

grant select on table "public"."NhatKySuDungs" to "anon";

grant trigger on table "public"."NhatKySuDungs" to "anon";

grant truncate on table "public"."NhatKySuDungs" to "anon";

grant update on table "public"."NhatKySuDungs" to "anon";

grant delete on table "public"."NhatKySuDungs" to "authenticated";

grant insert on table "public"."NhatKySuDungs" to "authenticated";

grant references on table "public"."NhatKySuDungs" to "authenticated";

grant select on table "public"."NhatKySuDungs" to "authenticated";

grant trigger on table "public"."NhatKySuDungs" to "authenticated";

grant truncate on table "public"."NhatKySuDungs" to "authenticated";

grant update on table "public"."NhatKySuDungs" to "authenticated";

grant delete on table "public"."NhatKySuDungs" to "service_role";

grant insert on table "public"."NhatKySuDungs" to "service_role";

grant references on table "public"."NhatKySuDungs" to "service_role";

grant select on table "public"."NhatKySuDungs" to "service_role";

grant trigger on table "public"."NhatKySuDungs" to "service_role";

grant truncate on table "public"."NhatKySuDungs" to "service_role";

grant update on table "public"."NhatKySuDungs" to "service_role";

grant delete on table "public"."PhienDangNhap" to "anon";

grant insert on table "public"."PhienDangNhap" to "anon";

grant references on table "public"."PhienDangNhap" to "anon";

grant select on table "public"."PhienDangNhap" to "anon";

grant trigger on table "public"."PhienDangNhap" to "anon";

grant truncate on table "public"."PhienDangNhap" to "anon";

grant update on table "public"."PhienDangNhap" to "anon";

grant delete on table "public"."PhienDangNhap" to "authenticated";

grant insert on table "public"."PhienDangNhap" to "authenticated";

grant references on table "public"."PhienDangNhap" to "authenticated";

grant select on table "public"."PhienDangNhap" to "authenticated";

grant trigger on table "public"."PhienDangNhap" to "authenticated";

grant truncate on table "public"."PhienDangNhap" to "authenticated";

grant update on table "public"."PhienDangNhap" to "authenticated";

grant delete on table "public"."PhienDangNhap" to "service_role";

grant insert on table "public"."PhienDangNhap" to "service_role";

grant references on table "public"."PhienDangNhap" to "service_role";

grant select on table "public"."PhienDangNhap" to "service_role";

grant trigger on table "public"."PhienDangNhap" to "service_role";

grant truncate on table "public"."PhienDangNhap" to "service_role";

grant update on table "public"."PhienDangNhap" to "service_role";

grant delete on table "public"."QuaTangKhoaHocs" to "anon";

grant insert on table "public"."QuaTangKhoaHocs" to "anon";

grant references on table "public"."QuaTangKhoaHocs" to "anon";

grant select on table "public"."QuaTangKhoaHocs" to "anon";

grant trigger on table "public"."QuaTangKhoaHocs" to "anon";

grant truncate on table "public"."QuaTangKhoaHocs" to "anon";

grant update on table "public"."QuaTangKhoaHocs" to "anon";

grant delete on table "public"."QuaTangKhoaHocs" to "authenticated";

grant insert on table "public"."QuaTangKhoaHocs" to "authenticated";

grant references on table "public"."QuaTangKhoaHocs" to "authenticated";

grant select on table "public"."QuaTangKhoaHocs" to "authenticated";

grant trigger on table "public"."QuaTangKhoaHocs" to "authenticated";

grant truncate on table "public"."QuaTangKhoaHocs" to "authenticated";

grant update on table "public"."QuaTangKhoaHocs" to "authenticated";

grant delete on table "public"."QuaTangKhoaHocs" to "service_role";

grant insert on table "public"."QuaTangKhoaHocs" to "service_role";

grant references on table "public"."QuaTangKhoaHocs" to "service_role";

grant select on table "public"."QuaTangKhoaHocs" to "service_role";

grant trigger on table "public"."QuaTangKhoaHocs" to "service_role";

grant truncate on table "public"."QuaTangKhoaHocs" to "service_role";

grant update on table "public"."QuaTangKhoaHocs" to "service_role";

grant delete on table "public"."TestCaseThucHanhs" to "anon";

grant insert on table "public"."TestCaseThucHanhs" to "anon";

grant references on table "public"."TestCaseThucHanhs" to "anon";

grant select on table "public"."TestCaseThucHanhs" to "anon";

grant trigger on table "public"."TestCaseThucHanhs" to "anon";

grant truncate on table "public"."TestCaseThucHanhs" to "anon";

grant update on table "public"."TestCaseThucHanhs" to "anon";

grant delete on table "public"."TestCaseThucHanhs" to "authenticated";

grant insert on table "public"."TestCaseThucHanhs" to "authenticated";

grant references on table "public"."TestCaseThucHanhs" to "authenticated";

grant select on table "public"."TestCaseThucHanhs" to "authenticated";

grant trigger on table "public"."TestCaseThucHanhs" to "authenticated";

grant truncate on table "public"."TestCaseThucHanhs" to "authenticated";

grant update on table "public"."TestCaseThucHanhs" to "authenticated";

grant delete on table "public"."TestCaseThucHanhs" to "service_role";

grant insert on table "public"."TestCaseThucHanhs" to "service_role";

grant references on table "public"."TestCaseThucHanhs" to "service_role";

grant select on table "public"."TestCaseThucHanhs" to "service_role";

grant trigger on table "public"."TestCaseThucHanhs" to "service_role";

grant truncate on table "public"."TestCaseThucHanhs" to "service_role";

grant update on table "public"."TestCaseThucHanhs" to "service_role";

grant delete on table "public"."ThongBaoEmailThanhToans" to "anon";

grant insert on table "public"."ThongBaoEmailThanhToans" to "anon";

grant references on table "public"."ThongBaoEmailThanhToans" to "anon";

grant select on table "public"."ThongBaoEmailThanhToans" to "anon";

grant trigger on table "public"."ThongBaoEmailThanhToans" to "anon";

grant truncate on table "public"."ThongBaoEmailThanhToans" to "anon";

grant update on table "public"."ThongBaoEmailThanhToans" to "anon";

grant delete on table "public"."ThongBaoEmailThanhToans" to "authenticated";

grant insert on table "public"."ThongBaoEmailThanhToans" to "authenticated";

grant references on table "public"."ThongBaoEmailThanhToans" to "authenticated";

grant select on table "public"."ThongBaoEmailThanhToans" to "authenticated";

grant trigger on table "public"."ThongBaoEmailThanhToans" to "authenticated";

grant truncate on table "public"."ThongBaoEmailThanhToans" to "authenticated";

grant update on table "public"."ThongBaoEmailThanhToans" to "authenticated";

grant delete on table "public"."ThongBaoEmailThanhToans" to "service_role";

grant insert on table "public"."ThongBaoEmailThanhToans" to "service_role";

grant references on table "public"."ThongBaoEmailThanhToans" to "service_role";

grant select on table "public"."ThongBaoEmailThanhToans" to "service_role";

grant trigger on table "public"."ThongBaoEmailThanhToans" to "service_role";

grant truncate on table "public"."ThongBaoEmailThanhToans" to "service_role";

grant update on table "public"."ThongBaoEmailThanhToans" to "service_role";

grant delete on table "public"."TienDoBaiHocs" to "anon";

grant insert on table "public"."TienDoBaiHocs" to "anon";

grant references on table "public"."TienDoBaiHocs" to "anon";

grant select on table "public"."TienDoBaiHocs" to "anon";

grant trigger on table "public"."TienDoBaiHocs" to "anon";

grant truncate on table "public"."TienDoBaiHocs" to "anon";

grant update on table "public"."TienDoBaiHocs" to "anon";

grant delete on table "public"."TienDoBaiHocs" to "authenticated";

grant insert on table "public"."TienDoBaiHocs" to "authenticated";

grant references on table "public"."TienDoBaiHocs" to "authenticated";

grant select on table "public"."TienDoBaiHocs" to "authenticated";

grant trigger on table "public"."TienDoBaiHocs" to "authenticated";

grant truncate on table "public"."TienDoBaiHocs" to "authenticated";

grant update on table "public"."TienDoBaiHocs" to "authenticated";

grant delete on table "public"."TienDoBaiHocs" to "service_role";

grant insert on table "public"."TienDoBaiHocs" to "service_role";

grant references on table "public"."TienDoBaiHocs" to "service_role";

grant select on table "public"."TienDoBaiHocs" to "service_role";

grant trigger on table "public"."TienDoBaiHocs" to "service_role";

grant truncate on table "public"."TienDoBaiHocs" to "service_role";

grant update on table "public"."TienDoBaiHocs" to "service_role";

grant delete on table "public"."VideoChapters" to "anon";

grant insert on table "public"."VideoChapters" to "anon";

grant references on table "public"."VideoChapters" to "anon";

grant select on table "public"."VideoChapters" to "anon";

grant trigger on table "public"."VideoChapters" to "anon";

grant truncate on table "public"."VideoChapters" to "anon";

grant update on table "public"."VideoChapters" to "anon";

grant delete on table "public"."VideoChapters" to "authenticated";

grant insert on table "public"."VideoChapters" to "authenticated";

grant references on table "public"."VideoChapters" to "authenticated";

grant select on table "public"."VideoChapters" to "authenticated";

grant trigger on table "public"."VideoChapters" to "authenticated";

grant truncate on table "public"."VideoChapters" to "authenticated";

grant update on table "public"."VideoChapters" to "authenticated";

grant delete on table "public"."VideoChapters" to "service_role";

grant insert on table "public"."VideoChapters" to "service_role";

grant references on table "public"."VideoChapters" to "service_role";

grant select on table "public"."VideoChapters" to "service_role";

grant trigger on table "public"."VideoChapters" to "service_role";

grant truncate on table "public"."VideoChapters" to "service_role";

grant update on table "public"."VideoChapters" to "service_role";

grant delete on table "public"."VideoQuizs" to "anon";

grant insert on table "public"."VideoQuizs" to "anon";

grant references on table "public"."VideoQuizs" to "anon";

grant select on table "public"."VideoQuizs" to "anon";

grant trigger on table "public"."VideoQuizs" to "anon";

grant truncate on table "public"."VideoQuizs" to "anon";

grant update on table "public"."VideoQuizs" to "anon";

grant delete on table "public"."VideoQuizs" to "authenticated";

grant insert on table "public"."VideoQuizs" to "authenticated";

grant references on table "public"."VideoQuizs" to "authenticated";

grant select on table "public"."VideoQuizs" to "authenticated";

grant trigger on table "public"."VideoQuizs" to "authenticated";

grant truncate on table "public"."VideoQuizs" to "authenticated";

grant update on table "public"."VideoQuizs" to "authenticated";

grant delete on table "public"."VideoQuizs" to "service_role";

grant insert on table "public"."VideoQuizs" to "service_role";

grant references on table "public"."VideoQuizs" to "service_role";

grant select on table "public"."VideoQuizs" to "service_role";

grant trigger on table "public"."VideoQuizs" to "service_role";

grant truncate on table "public"."VideoQuizs" to "service_role";

grant update on table "public"."VideoQuizs" to "service_role";

grant delete on table "public"."YeuCauRutTienGiangViens" to "anon";

grant insert on table "public"."YeuCauRutTienGiangViens" to "anon";

grant references on table "public"."YeuCauRutTienGiangViens" to "anon";

grant select on table "public"."YeuCauRutTienGiangViens" to "anon";

grant trigger on table "public"."YeuCauRutTienGiangViens" to "anon";

grant truncate on table "public"."YeuCauRutTienGiangViens" to "anon";

grant update on table "public"."YeuCauRutTienGiangViens" to "anon";

grant delete on table "public"."YeuCauRutTienGiangViens" to "authenticated";

grant insert on table "public"."YeuCauRutTienGiangViens" to "authenticated";

grant references on table "public"."YeuCauRutTienGiangViens" to "authenticated";

grant select on table "public"."YeuCauRutTienGiangViens" to "authenticated";

grant trigger on table "public"."YeuCauRutTienGiangViens" to "authenticated";

grant truncate on table "public"."YeuCauRutTienGiangViens" to "authenticated";

grant update on table "public"."YeuCauRutTienGiangViens" to "authenticated";

grant delete on table "public"."YeuCauRutTienGiangViens" to "service_role";

grant insert on table "public"."YeuCauRutTienGiangViens" to "service_role";

grant references on table "public"."YeuCauRutTienGiangViens" to "service_role";

grant select on table "public"."YeuCauRutTienGiangViens" to "service_role";

grant trigger on table "public"."YeuCauRutTienGiangViens" to "service_role";

grant truncate on table "public"."YeuCauRutTienGiangViens" to "service_role";

grant update on table "public"."YeuCauRutTienGiangViens" to "service_role";

grant delete on table "public"."__EFMigrationsHistory" to "anon";

grant insert on table "public"."__EFMigrationsHistory" to "anon";

grant references on table "public"."__EFMigrationsHistory" to "anon";

grant select on table "public"."__EFMigrationsHistory" to "anon";

grant trigger on table "public"."__EFMigrationsHistory" to "anon";

grant truncate on table "public"."__EFMigrationsHistory" to "anon";

grant update on table "public"."__EFMigrationsHistory" to "anon";

grant delete on table "public"."__EFMigrationsHistory" to "authenticated";

grant insert on table "public"."__EFMigrationsHistory" to "authenticated";

grant references on table "public"."__EFMigrationsHistory" to "authenticated";

grant select on table "public"."__EFMigrationsHistory" to "authenticated";

grant trigger on table "public"."__EFMigrationsHistory" to "authenticated";

grant truncate on table "public"."__EFMigrationsHistory" to "authenticated";

grant update on table "public"."__EFMigrationsHistory" to "authenticated";

grant delete on table "public"."__EFMigrationsHistory" to "service_role";

grant insert on table "public"."__EFMigrationsHistory" to "service_role";

grant references on table "public"."__EFMigrationsHistory" to "service_role";

grant select on table "public"."__EFMigrationsHistory" to "service_role";

grant trigger on table "public"."__EFMigrationsHistory" to "service_role";

grant truncate on table "public"."__EFMigrationsHistory" to "service_role";

grant update on table "public"."__EFMigrationsHistory" to "service_role";


