import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { AnimatedPressable } from '../../../shared/components/animated-pressable';
import { EndPhongVanResponse, LichSuPhongVan, PhongVanAIService, TinhCachAI } from '../services/phong-van-ai.service';

const C={orange:'#F69050',purple:'#8B5CF6',bg:'#F9FAFB',white:'#FFF',text:'#111827',muted:'#6B7280',border:'#E5E7EB',danger:'#EF4444',success:'#10B981'};
type Message={role:'ai'|'user';content:string};

export default function PhongVanAIScreen(){
 const router=useRouter(); const [position,setPosition]=useState('Frontend Developer'); const [level,setLevel]=useState('Junior'); const [personality,setPersonality]=useState(TinhCachAI.Normal); const [session,setSession]=useState<number|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [answer,setAnswer]=useState(''); const [loading,setLoading]=useState(false); const [finished,setFinished]=useState(false); const [result,setResult]=useState<EndPhongVanResponse|null>(null); const [history,setHistory]=useState<LichSuPhongVan[]>([]); const [error,setError]=useState<string|null>(null); const inFlight=useRef(false);
 const loadHistory=useCallback(async()=>{try{setHistory(await PhongVanAIService.getHistory());}catch{setError('Không thể tải lịch sử phỏng vấn.');}},[]);
 useEffect(()=>{void loadHistory();},[loadHistory]);
 const start=async()=>{if(inFlight.current)return;if(!position.trim()||!level.trim()){setError('Vui lòng nhập vị trí ứng tuyển và cấp độ.');return;}inFlight.current=true;setLoading(true);setError(null);try{const data=await PhongVanAIService.startInterview({viTriUngTuyen:position.trim(),capDo:level.trim(),tinhCachAI:personality,soLuongCauHoi:3});if(!data.maPhongVan||!data.cauHoiDauTien?.trim())throw new Error('INVALID_SESSION');setSession(data.maPhongVan);setMessages([{role:'ai',content:data.cauHoiDauTien}]);setFinished(false);setResult(null);}catch{setError('Không thể bắt đầu phỏng vấn.');}finally{inFlight.current=false;setLoading(false);}};
 const send=async()=>{const text=answer.trim();if(!session||!text||inFlight.current)return;inFlight.current=true;setLoading(true);setError(null);setAnswer('');setMessages(v=>[...v,{role:'user',content:text}]);try{const data=await PhongVanAIService.answerQuestion({maPhongVan:session,cauTraLoi:text});const content=[data.nhanXetCauTruoc,data.cauHoiTiepTheo].filter(Boolean).join('\n\n');if(content)setMessages(v=>[...v,{role:'ai',content}]);setFinished(data.isFinished);}catch{setAnswer(text);setError('Không thể gửi câu trả lời. Nội dung đã được giữ lại.');}finally{inFlight.current=false;setLoading(false);}};
 const end=async()=>{if(!session||inFlight.current)return;inFlight.current=true;setLoading(true);setError(null);try{setResult(await PhongVanAIService.endInterview(session));setFinished(true);await loadHistory();}catch{setError('Không thể kết thúc và lấy kết quả phỏng vấn.');}finally{inFlight.current=false;setLoading(false);}};
 const reset=()=>{if(inFlight.current)return;setSession(null);setMessages([]);setAnswer('');setFinished(false);setResult(null);setError(null);};
 return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><AnimatedPressable style={s.icon} onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color={C.text}/></AnimatedPressable><Text style={s.title}>Phỏng vấn AI</Text><View style={s.icon}/></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
 {!session?<><Text style={s.heading}>Thiết lập phỏng vấn</Text><Field label="Vị trí ứng tuyển" value={position} onChange={setPosition}/><Field label="Cấp độ" value={level} onChange={setLevel}/><Text style={s.label}>Phong cách AI</Text><View style={s.choices}>{[[TinhCachAI.Friendly,'Thân thiện'],[TinhCachAI.Normal,'Bình thường'],[TinhCachAI.Strict,'Nghiêm khắc']].map(([value,label])=><AnimatedPressable key={value} style={[s.choice,personality===value&&s.choiceActive]} onPress={()=>setPersonality(value as TinhCachAI)}><Text style={personality===value?s.choiceTextActive:s.choiceText}>{label}</Text></AnimatedPressable>)}</View><AnimatedPressable style={[s.button,loading&&s.disabled]} onPress={()=>void start()} disabled={loading}>{loading?<ActivityIndicator color={C.white}/>:<Text style={s.buttonText}>Bắt đầu</Text>}</AnimatedPressable></>:<><Text style={s.heading}>{position} · {level}</Text>{messages.map((m,i)=><View key={`${m.role}-${i}`} style={[s.bubble,m.role==='user'?s.user:s.ai]}><Text style={m.role==='user'?s.userText:s.aiText}>{m.content}</Text></View>)}{loading&&<ActivityIndicator color={C.purple} style={{margin:12}}/>}{!finished&&<><TextInput style={[s.input,s.multiline]} value={answer} onChangeText={setAnswer} placeholder="Nhập câu trả lời..." placeholderTextColor={C.muted} multiline/><AnimatedPressable style={[s.button,(!answer.trim()||loading)&&s.disabled]} onPress={()=>void send()} disabled={!answer.trim()||loading}><Text style={s.buttonText}>Gửi câu trả lời</Text></AnimatedPressable></>}{finished&&!result&&<AnimatedPressable style={s.button} onPress={()=>void end()} disabled={loading}><Text style={s.buttonText}>Xem kết quả</Text></AnimatedPressable>}{result&&<View style={s.result}><Text style={s.score}>{result.diemSo}/100</Text><Text style={s.aiText}>{result.danhGiaChung}</Text><List title="Điểm mạnh" items={result.diemManh}/><List title="Cần cải thiện" items={result.canCaiThien}/><List title="Lời khuyên" items={[result.loiKhuyen]}/><AnimatedPressable style={s.button} onPress={reset}><Text style={s.buttonText}>Phỏng vấn mới</Text></AnimatedPressable></View>}</>}
 {error&&<Text style={s.error}>{error}</Text>}<Text style={s.heading}>Lịch sử</Text>{history.length===0?<Text style={s.muted}>Chưa có phiên phỏng vấn.</Text>:history.map(h=><View key={h.maPhongVan} style={s.history}><Text style={s.historyTitle}>{h.viTriUngTuyen} · {h.capDo}</Text><Text style={s.muted}>{new Date(h.ngayPhongVan).toLocaleDateString('vi-VN')} · {h.diemSo}/100</Text></View>)}</ScrollView></KeyboardAvoidingView>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <View style={{marginTop:14}}><Text style={s.label}>{label}</Text><TextInput style={s.input} value={value} onChangeText={onChange}/></View>};function List({title,items}:{title:string;items:string[]}){return <View style={{marginTop:14}}><Text style={s.historyTitle}>{title}</Text>{items.filter(Boolean).map((x,i)=><Text key={`${x}-${i}`} style={s.muted}>• {x}</Text>)}</View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg,paddingTop:Platform.OS==='android'?24:0},header:{minHeight:64,flexDirection:'row',alignItems:'center',backgroundColor:C.white,borderBottomWidth:1,borderBottomColor:C.border,paddingHorizontal:12},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{flex:1,textAlign:'center',fontSize:20,fontWeight:'700',color:C.text},content:{padding:16,paddingBottom:40},heading:{fontSize:21,fontWeight:'800',color:C.text,marginTop:12,marginBottom:8},label:{fontWeight:'600',color:C.text,marginBottom:6,marginTop:14},input:{minHeight:48,borderWidth:1,borderColor:C.border,borderRadius:12,backgroundColor:C.white,paddingHorizontal:14,color:C.text,fontSize:16},multiline:{minHeight:90,textAlignVertical:'top',paddingTop:12,marginTop:14},choices:{flexDirection:'row',gap:8},choice:{flex:1,minHeight:44,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.border,borderRadius:10,backgroundColor:C.white},choiceActive:{backgroundColor:C.purple,borderColor:C.purple},choiceText:{color:C.text,fontSize:12},choiceTextActive:{color:C.white,fontWeight:'700',fontSize:12},button:{minHeight:50,marginTop:16,borderRadius:12,backgroundColor:C.orange,alignItems:'center',justifyContent:'center'},buttonText:{color:C.white,fontWeight:'800'},disabled:{opacity:.5},bubble:{maxWidth:'90%',padding:14,borderRadius:15,marginTop:12},user:{alignSelf:'flex-end',backgroundColor:C.orange},ai:{alignSelf:'flex-start',backgroundColor:C.white,borderWidth:1,borderColor:C.border},userText:{color:C.white,lineHeight:22},aiText:{color:C.text,lineHeight:22},error:{color:C.danger,marginTop:12},result:{marginTop:16,padding:18,borderRadius:16,backgroundColor:C.white,borderWidth:1,borderColor:C.border},score:{fontSize:30,fontWeight:'900',color:C.success,textAlign:'center',marginBottom:10},history:{marginTop:10,padding:14,borderRadius:12,backgroundColor:C.white,borderWidth:1,borderColor:C.border},historyTitle:{fontWeight:'700',color:C.text},muted:{color:C.muted,lineHeight:21,marginTop:4}});
