import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { AnimatedPressable } from '../../../shared/components/animated-pressable';
import { SinhDoAnAIService, SinhDoAnResponse } from '../services/sinh-do-an-ai.service';
const C={orange:'#F69050',purple:'#8B5CF6',bg:'#F9FAFB',white:'#FFF',text:'#111827',muted:'#6B7280',border:'#E5E7EB',danger:'#EF4444'};
export default function SinhDoAnAIScreen(){const router=useRouter();const [career,setCareer]=useState('Frontend Developer');const [tech,setTech]=useState('React, TypeScript');const [level,setLevel]=useState('Cơ bản');const [difficulty,setDifficulty]=useState('');const [changes,setChanges]=useState('');const [result,setResult]=useState<SinhDoAnResponse|null>(null);const [loading,setLoading]=useState(false);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState<string|null>(null);const inFlight=useRef(false);
 const generate=async()=>{if(!career.trim()||!tech.trim()||!level.trim()||inFlight.current)return;inFlight.current=true;setLoading(true);setError(null);try{setResult(await SinhDoAnAIService.generate({mucTieuNgheNghiep:career.trim(),ngonNguCongNghe:tech.trim(),capDo:level.trim()}));}catch{setError('Không thể sinh đồ án AI. Vui lòng thử lại.');}finally{inFlight.current=false;setLoading(false);}};
 const submit=async()=>{if(!result||inFlight.current)return;inFlight.current=true;setSubmitting(true);setError(null);try{const data=await SinhDoAnAIService.submit({maDoAn:result.maDoAn||undefined,tenDoAn:result.tenDoAn,moTa:result.moTa,yeuCauChucNang:result.yeuCauChucNang.map(x=>x.tenChucNang),cauTrucDatabase:result.cauTrucDatabase,mucTieuNgheNghiep:career,ngonNguCongNghe:tech,ghiChuThayDoi:changes.trim(),khoKhan:difficulty.trim(),tienDoHoanThanh:'Nộp đồ án để tham gia phỏng vấn'});router.push({pathname:'/phong-van-do-an',params:{sessionId:data.sessionId,cauHoiDauTien:data.cauHoiDauTien,tenDoAn:result.tenDoAn}});}catch{setError('Không thể nộp đồ án và tạo phiên phỏng vấn.');}finally{inFlight.current=false;setSubmitting(false);}};
 return <KeyboardAvoidingView style={s.screen} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><AnimatedPressable style={s.icon} onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color={C.text}/></AnimatedPressable><Text style={s.title}>Sinh đồ án AI</Text><View style={s.icon}/></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.heading}>Yêu cầu đồ án</Text><Field label="Mục tiêu nghề nghiệp" value={career} onChange={setCareer}/><Field label="Ngôn ngữ / công nghệ" value={tech} onChange={setTech}/><Field label="Cấp độ" value={level} onChange={setLevel}/>{error&&<Text style={s.error}>{error}</Text>}<AnimatedPressable style={[s.button,loading&&s.disabled]} onPress={()=>void generate()} disabled={loading}>{loading?<ActivityIndicator color={C.white}/>:<Text style={s.buttonText}>{result?'Tạo lại đồ án':'Tạo đồ án'}</Text>}</AnimatedPressable>{result&&<View style={s.result}><Text style={s.resultTitle}>{result.tenDoAn}</Text><Text style={s.body}>{result.moTa}</Text><Text style={s.section}>Yêu cầu chức năng</Text>{result.yeuCauChucNang.map((item,index)=><View key={`${item.ngay}-${index}`} style={s.feature}><View style={s.number}><Text style={s.numberText}>{index+1}</Text></View><View style={{flex:1}}><Text style={s.featureTitle}>{item.tenChucNang}</Text><Text style={s.body}>{item.chiTietYeuCau}</Text>{item.goiYFileNop?<Text style={s.hint}>Gợi ý file: {item.goiYFileNop}</Text>:null}</View></View>)}<Text style={s.section}>Cấu trúc database</Text><Text style={s.code}>{result.cauTrucDatabase}</Text><Field label="Khó khăn gặp phải" value={difficulty} onChange={setDifficulty} multiline/><Field label="Ghi chú thay đổi" value={changes} onChange={setChanges} multiline/><AnimatedPressable style={[s.button,submitting&&s.disabled]} onPress={()=>void submit()} disabled={submitting}>{submitting?<ActivityIndicator color={C.white}/>:<Text style={s.buttonText}>Nộp và vào phỏng vấn</Text>}</AnimatedPressable></View>}</ScrollView></KeyboardAvoidingView>}
function Field({label,value,onChange,multiline}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean}){return <View style={{marginTop:14}}><Text style={s.label}>{label}</Text><TextInput style={[s.input,multiline&&s.multiline]} value={value} onChangeText={onChange} multiline={multiline}/></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:C.bg,paddingTop:Platform.OS==='android'?24:0},header:{minHeight:64,flexDirection:'row',alignItems:'center',backgroundColor:C.white,borderBottomWidth:1,borderBottomColor:C.border,paddingHorizontal:12},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{flex:1,textAlign:'center',fontSize:20,fontWeight:'700',color:C.text},content:{padding:16,paddingBottom:40},heading:{fontSize:22,fontWeight:'800',color:C.text},label:{fontWeight:'600',color:C.text,marginBottom:6},input:{minHeight:48,borderWidth:1,borderColor:C.border,borderRadius:12,backgroundColor:C.white,paddingHorizontal:14,color:C.text,fontSize:16},multiline:{minHeight:80,paddingTop:12,textAlignVertical:'top'},button:{minHeight:50,marginTop:18,borderRadius:12,backgroundColor:C.orange,alignItems:'center',justifyContent:'center'},buttonText:{color:C.white,fontWeight:'800'},disabled:{opacity:.5},error:{color:C.danger,marginTop:12},result:{marginTop:22,padding:18,borderRadius:16,borderWidth:1,borderColor:C.border,backgroundColor:C.white},resultTitle:{fontSize:23,fontWeight:'800',color:C.text},body:{color:C.muted,lineHeight:21,marginTop:6},section:{fontSize:17,fontWeight:'800',color:C.text,marginTop:20,marginBottom:6},feature:{flexDirection:'row',marginTop:12},number:{width:30,height:30,borderRadius:15,backgroundColor:C.purple,alignItems:'center',justifyContent:'center',marginRight:10},numberText:{color:C.white,fontWeight:'800'},featureTitle:{fontWeight:'700',color:C.text},hint:{color:C.purple,marginTop:5},code:{fontFamily:Platform.OS==='ios'?'Menlo':'monospace',backgroundColor:'#111827',color:C.white,padding:12,borderRadius:10,lineHeight:20}});
