<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>educodeai_server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\GiangVien\" />
    <Folder Include="Controllers\HocVien\" />
    <Folder Include="Controllers\QuanTriVien\" />
    <Folder Include="DTOs\KhoaHoc\" />
    <Folder Include="DTOs\BaiTap\" />
    <Folder Include="DTOs\AI\" />
    <Folder Include="DTOs\NguoiDung\" />
    <Folder Include="DTOs\XacThuc\" />
    <Folder Include="Models\" />
    <Folder Include="Helpers\" />
  </ItemGroup>

</Project>
