import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useAuth } from '../../auth/hooks/use-auth';
import { DiscoveryService, DiscoveryCourse } from '../services/discovery.service';

const C = { primary: '#f69050', dark: '#111827', muted: '#6b7280', bg: '#f9fafb', border: '#e5e7eb', white: '#fff' };
export default function PublicHomeScreen() {
  const router = useRouter(); const { session, logout } = useAuth(); const user = session?.user;
  const [courses, setCourses] = useState<DiscoveryCourse[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async (value = '') => { try { setLoading(true); setError(''); setCourses(await DiscoveryService.getCourses(value)); } catch { setError('Không thể tải danh sách khóa học.'); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(() => void load(search), 350); return () => clearTimeout(timer); }, [search]);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={styles.brand}>EduCodeAI</Text><Text style={styles.tagline}>{user ? `Xin chào, ${user.hoTen}` : 'Học để tạo ra sản phẩm thật'}</Text></View><Pressable style={styles.login} onPress={() => user ? void logout() : router.push('/auth/login' as never)}><Text style={styles.loginText}>{user ? 'Đăng xuất' : 'Đăng nhập'}</Text></Pressable></View>
    <View style={styles.hero}><Text style={styles.heroTitle}>Khám phá khóa học</Text><Text style={styles.heroText}>Học theo lộ trình thực tế cùng EduCodeAI.</Text></View>
    <View style={styles.search}><Ionicons name="search" size={20} color={C.muted}/><TextInput value={search} onChangeText={setSearch} placeholder="Tìm kiếm khóa học..." style={styles.searchInput}/></View>
    <Text style={styles.section}>Khóa học nổi bật</Text>{loading ? <ActivityIndicator color={C.primary} style={styles.loader}/> : error ? <State text={error} action="Thử lại" onPress={() => void load(search)}/> : courses.length === 0 ? <State text="Chưa có khóa học phù hợp."/> : courses.map(course => <Pressable key={course.maKhoaHoc} style={styles.card} onPress={() => router.push(`/khoa-hoc/${course.maKhoaHoc}` as never)}><View style={styles.thumb}><Ionicons name="book-outline" size={30} color={C.primary}/></View><View style={styles.cardBody}><Text style={styles.cardTitle} numberOfLines={2}>{course.tenKhoaHoc}</Text><Text style={styles.meta}>{course.linhVuc || 'Chung'} · {course.trinhDo || 'Mọi trình độ'}</Text><Text style={styles.rating}>★ {(course.diemDanhGiaTB ?? 0).toFixed(1)} · {course.thoiLuongGio ?? 0} giờ học</Text></View></Pressable>)}
  </ScrollView><View style={styles.nav}><Nav icon="home" label="Trang chủ" active onPress={() => router.replace('/')}/><Nav icon="book-outline" label="Khóa học" onPress={() => router.replace('/')}/><Nav icon="trophy-outline" label="Thử thách" onPress={() => router.push('/thu-thach')}/><Nav icon="person-outline" label="Tài khoản" onPress={() => router.push('/auth/login' as never)}/></View></SafeAreaView>;
}
function Nav({icon,label,active,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;active?:boolean;onPress:()=>void}) { return <Pressable style={styles.navItem} onPress={onPress}><Ionicons name={icon} size={22} color={active ? C.primary : C.muted}/><Text style={[styles.navLabel,active&&styles.active]}>{label}</Text></Pressable>; }
function State({text,action,onPress}:{text:string;action?:string;onPress?:()=>void}) { return <View style={styles.state}><Text style={styles.meta}>{text}</Text>{action&&<Pressable onPress={onPress}><Text style={styles.retry}>{action}</Text></Pressable>}</View>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},content:{padding:20,paddingBottom:100},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:20},brand:{fontSize:24,fontWeight:'800',color:C.dark},tagline:{color:C.muted,marginTop:3},login:{borderWidth:1,borderColor:C.primary,borderRadius:10,padding:10},loginText:{color:C.primary,fontWeight:'700'},hero:{backgroundColor:C.primary,borderRadius:18,padding:20,marginBottom:16},heroTitle:{color:C.white,fontWeight:'800',fontSize:24},heroText:{color:'#fff7ed',marginTop:7},search:{backgroundColor:C.white,borderWidth:1,borderColor:C.border,borderRadius:12,flexDirection:'row',alignItems:'center',paddingHorizontal:12},searchInput:{flex:1,padding:13,fontSize:16},section:{fontSize:20,fontWeight:'800',color:C.dark,marginVertical:18},loader:{marginTop:30},card:{backgroundColor:C.white,borderWidth:1,borderColor:C.border,borderRadius:14,padding:12,flexDirection:'row',marginBottom:12},thumb:{width:86,height:86,borderRadius:10,backgroundColor:'#fff3ed',alignItems:'center',justifyContent:'center'},cardBody:{flex:1,paddingLeft:12},cardTitle:{fontSize:16,fontWeight:'800',color:C.dark},meta:{color:C.muted,marginTop:6,lineHeight:20},rating:{color:'#d97706',marginTop:8,fontWeight:'600'},state:{alignItems:'center',padding:30},retry:{color:C.primary,fontWeight:'700',marginTop:12},nav:{position:'absolute',bottom:0,left:0,right:0,height:72,backgroundColor:C.white,borderTopWidth:1,borderTopColor:C.border,flexDirection:'row',justifyContent:'space-around'},navItem:{alignItems:'center',justifyContent:'center',minWidth:64},navLabel:{fontSize:11,color:C.muted,marginTop:4},active:{color:C.primary,fontWeight:'700'}});
