import { Ionicons } from '@expo/vector-icons';
import { useCallback, useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { AccountScreen, StateMessage, accountColors } from '../components/account-ui';
import { AccountService } from '../services/account.service';
import { useAuth } from '../../auth/hooks/use-auth';
import type { DeviceSession } from '../types/account.types';
import { getAccountErrorMessage } from '../types/account.types';

export interface DevicesScreenProps { onCurrentSessionRevoked?: () => void | Promise<void> }
export default function DevicesScreen({ onCurrentSessionRevoked }: DevicesScreenProps) {
  const { clearSession } = useAuth();
  const [devices, setDevices] = useState<DeviceSession[]>([]); const [selected, setSelected] = useState<number[]>([]); const [all, setAll] = useState(false); const [otp, setOtp] = useState(''); const [otpSent, setOtpSent] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setDevices(await AccountService.getDevices()); } catch (e) { setError(getAccountErrorMessage(e, 'Không thể tải danh sách thiết bị.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const toggle = (id: number) => setSelected(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]);
  const requestOtp = async () => { if (busy || (!all && selected.length === 0)) return; setBusy(true); try { await AccountService.requestRemoteLogoutOtp(); setOtpSent(true); Alert.alert('Đã gửi OTP', 'Vui lòng kiểm tra kênh xác thực của tài khoản.'); } catch (e) { Alert.alert('Không thể gửi OTP', getAccountErrorMessage(e, 'Vui lòng thử lại.')); } finally { setBusy(false); } };
  const confirm = async () => { if (busy) return; if (!/^\d{4,8}$/.test(otp.trim())) return Alert.alert('OTP chưa hợp lệ', 'OTP phải gồm từ 4 đến 8 chữ số.'); setBusy(true); try { await AccountService.confirmRemoteLogout({ OtpCode: otp.trim(), DangXuatTatCa: all, DanhSachMaPhien: all ? [] : selected }); const revokedCurrent = all || devices.some(x => x.isCurrentDevice && selected.includes(x.maPhien)); if (revokedCurrent) { await clearSession('sessionExpired'); await onCurrentSessionRevoked?.(); return; } setOtp(''); setOtpSent(false); setSelected([]); setAll(false); Alert.alert('Thành công', 'Đã thu hồi các phiên được chọn.'); await load(); } catch (e) { Alert.alert('Không thể thu hồi phiên', getAccountErrorMessage(e, 'Vui lòng kiểm tra OTP.')); } finally { setBusy(false); } };
  if (loading) return <AccountScreen title="Thiết bị"><StateMessage loading message="Đang tải thiết bị…" /></AccountScreen>;
  if (error) return <AccountScreen title="Thiết bị"><StateMessage message={error} onRetry={() => void load()} /></AccountScreen>;
  return <AccountScreen title="Quản lý thiết bị">
    <View style={styles.allRow}><View style={{ flex: 1 }}><Text style={styles.allTitle}>Đăng xuất tất cả thiết bị</Text><Text style={styles.muted}>Bao gồm phiên hiện tại; ứng dụng sẽ yêu cầu đăng nhập lại</Text></View><Switch accessibilityLabel="Đăng xuất tất cả thiết bị" value={all} onValueChange={value => { setAll(value); if (value) setSelected([]); }} trackColor={{ true: accountColors.primary }} /></View>
    {devices.length === 0 ? <StateMessage message="Chưa có phiên đăng nhập nào." onRetry={() => void load()} /> : devices.map(device => <Pressable key={device.maPhien} disabled={all} accessibilityRole="checkbox" accessibilityState={{ checked: all || selected.includes(device.maPhien), disabled: all }} onPress={() => toggle(device.maPhien)} style={[styles.device, (all || selected.includes(device.maPhien)) && styles.selected]}>
      <Ionicons name="phone-portrait-outline" size={26} color={accountColors.primary} /><View style={styles.deviceInfo}><Text style={styles.deviceName}>{device.tenThietBi || 'Thiết bị không xác định'}</Text><Text style={styles.muted}>{device.isCurrentDevice ? 'Thiết bị hiện tại · ' : ''}{formatDate(device.thoiGianHoatDongCuoi)}</Text></View><Ionicons name={(all || selected.includes(device.maPhien)) ? 'checkbox' : 'square-outline'} size={25} color={accountColors.primary} />
    </Pressable>)}
    {!otpSent ? <Pressable accessibilityRole="button" disabled={busy || (!all && selected.length === 0)} onPress={() => void requestOtp()} style={[styles.button, (busy || (!all && selected.length === 0)) && styles.disabled]}><Text style={styles.buttonText}>{busy ? 'Đang gửi…' : 'Gửi OTP xác nhận'}</Text></Pressable> : <View style={styles.otpCard}><Text style={styles.label}>Mã OTP</Text><TextInput accessibilityLabel="Mã OTP" value={otp} onChangeText={value => setOtp(value.replace(/\D/g, ''))} keyboardType="number-pad" maxLength={8} style={styles.input} /><Pressable accessibilityRole="button" disabled={busy} onPress={() => void confirm()} style={[styles.button, busy && styles.disabled]}><Text style={styles.buttonText}>{busy ? 'Đang xác nhận…' : 'Xác nhận đăng xuất'}</Text></Pressable></View>}
  </AccountScreen>;
}
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Chưa có thời gian hoạt động' : `Hoạt động ${date.toLocaleString('vi-VN')}`; }
const styles = StyleSheet.create({ allRow: { flexDirection: 'row', alignItems: 'center', padding: 18, borderRadius: 18, backgroundColor: accountColors.card, marginBottom: 14 }, allTitle: { color: accountColors.text, fontWeight: '800', fontSize: 16 }, muted: { color: accountColors.muted, fontSize: 13, marginTop: 4 }, device: { flexDirection: 'row', alignItems: 'center', padding: 17, borderRadius: 18, backgroundColor: accountColors.card, borderWidth: 1, borderColor: accountColors.border, marginBottom: 10 }, selected: { borderColor: accountColors.primary, backgroundColor: accountColors.primaryLight }, deviceInfo: { flex: 1, marginHorizontal: 13 }, deviceName: { color: accountColors.text, fontWeight: '800' }, button: { minHeight: 52, backgroundColor: accountColors.primary, borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginTop: 16 }, buttonText: { color: '#fff', fontWeight: '900' }, disabled: { opacity: .45 }, otpCard: { marginTop: 16, padding: 18, borderRadius: 18, backgroundColor: accountColors.card }, label: { color: accountColors.text, fontWeight: '700', marginBottom: 8 }, input: { borderWidth: 1, borderColor: accountColors.border, borderRadius: 14, minHeight: 52, paddingHorizontal: 14, fontSize: 20, letterSpacing: 5, color: accountColors.text } });
